import { Badge } from '../types';

export const BADGES: Badge[] = [
  {
    id: 'first_step',
    name: 'Super départ',
    icon: '⭐',
    description: 'Première routine terminée.',
    requirement: 1,
    requirementType: 'routines',
  },
  {
    id: 'getting_started',
    name: 'En route !',
    icon: '🛤️',
    description: '5 routines terminées.',
    requirement: 5,
    requirementType: 'routines',
  },
  {
    id: 'routine_10',
    name: 'Champion',
    icon: '🏆',
    description: '10 routines terminées.',
    requirement: 10,
    requirementType: 'routines',
  },
  {
    id: 'routine_25',
    name: 'Routines bien lancées',
    icon: '⚙️',
    description: '25 routines terminées.',
    requirement: 25,
    requirementType: 'routines',
  },
  {
    id: 'routine_50',
    name: 'Diamant',
    icon: '💎',
    description: '50 routines terminées.',
    requirement: 50,
    requirementType: 'routines',
  },
  {
    id: 'routine_100',
    name: 'Invincible',
    icon: '🛡️',
    description: '100 routines terminées.',
    requirement: 100,
    requirementType: 'routines',
  },
  {
    id: 'routine_250',
    name: 'Maître des routines',
    icon: '👑',
    description: '250 routines terminées.',
    requirement: 250,
    requirementType: 'routines',
  },
  {
    id: 'activity_1',
    name: 'Première découverte',
    icon: '🌱',
    description: 'Première activité terminée ensemble.',
    requirement: 1,
    requirementType: 'activities',
  },
  {
    id: 'activity_5',
    name: 'Curieux ensemble',
    icon: '🔎',
    description: '5 activités terminées ensemble.',
    requirement: 5,
    requirementType: 'activities',
  },
  {
    id: 'activity_15',
    name: 'Explorateur d’idées',
    icon: '🌈',
    description: '15 activités terminées ensemble.',
    requirement: 15,
    requirementType: 'activities',
  },
  {
    id: 'autonomy_1',
    name: 'Je prends confiance',
    icon: '🪴',
    description: 'Première activité en autonomie forte, avec l’adulte à proximité.',
    requirement: 1,
    requirementType: 'autonomy',
  },
  {
    id: 'autonomy_5',
    name: 'Petit élan',
    icon: '🪽',
    description: '5 activités en autonomie forte, toujours accompagnées.',
    requirement: 5,
    requirementType: 'autonomy',
  },
  {
    id: 'streak_3',
    name: 'En feu !',
    icon: '🔥',
    description: '3 jours de suite, bravo !',
    requirement: 3,
    requirementType: 'streak',
  },
  {
    id: 'streak_5',
    name: 'Régulier',
    icon: '📅',
    description: '5 jours de suite.',
    requirement: 5,
    requirementType: 'streak',
  },
  {
    id: 'streak_7',
    name: 'Fusée',
    icon: '🚀',
    description: '7 jours de suite.',
    requirement: 7,
    requirementType: 'streak',
  },
  {
    id: 'streak_14',
    name: 'Super régularité',
    icon: '💪',
    description: '14 jours de suite.',
    requirement: 14,
    requirementType: 'streak',
  },
  {
    id: 'streak_30',
    name: 'Légende',
    icon: '👑',
    description: '30 jours de suite.',
    requirement: 30,
    requirementType: 'streak',
  },
  {
    id: 'streak_60',
    name: 'Imbattable',
    icon: '⚡',
    description: '60 jours de suite.',
    requirement: 60,
    requirementType: 'streak',
  },
  {
    id: 'streak_100',
    name: 'Mythique',
    icon: '🌠',
    description: '100 jours de suite.',
    requirement: 100,
    requirementType: 'streak',
  },
  {
    id: 'stars_1',
    name: 'Première étoile',
    icon: '⭐',
    description: 'Première étoile gagnée.',
    requirement: 1,
    requirementType: 'stars',
  },
  {
    id: 'stars_10',
    name: 'Petit collectionneur',
    icon: '✨',
    description: '10 étoiles collectées.',
    requirement: 10,
    requirementType: 'stars',
  },
  {
    id: 'stars_25',
    name: 'Chasseur d’étoiles',
    icon: '🌟',
    description: '25 étoiles collectées.',
    requirement: 25,
    requirementType: 'stars',
  },
  {
    id: 'stars_50',
    name: 'Brillant',
    icon: '💫',
    description: '50 étoiles collectées.',
    requirement: 50,
    requirementType: 'stars',
  },
  {
    id: 'stars_100',
    name: 'Collectionneur',
    icon: '🌠',
    description: '100 étoiles collectées.',
    requirement: 100,
    requirementType: 'stars',
  },
  {
    id: 'stars_250',
    name: 'Galaxie',
    icon: '🌌',
    description: '250 étoiles collectées.',
    requirement: 250,
    requirementType: 'stars',
  },
  {
    id: 'stars_500',
    name: 'Univers',
    icon: '🪐',
    description: '500 étoiles collectées.',
    requirement: 500,
    requirementType: 'stars',
  },
];
