import { Badge } from '../types';

export const BADGES: Badge[] = [
  {
    id: 'first_step',
    name: 'Super depart',
    icon: '⭐',
    description: 'Tu as complete ta premiere routine !',
    requirement: 1,
    requirementType: 'routines',
  },
  {
    id: 'getting_started',
    name: 'En route !',
    icon: '🛤️',
    description: '5 routines completees, tu prends ton elan !',
    requirement: 5,
    requirementType: 'routines',
  },
  {
    id: 'routine_10',
    name: 'Champion',
    icon: '🏆',
    description: '10 routines completees !',
    requirement: 10,
    requirementType: 'routines',
  },
  {
    id: 'routine_25',
    name: 'Machine a routines',
    icon: '⚙️',
    description: '25 routines completees, rien ne t arrete !',
    requirement: 25,
    requirementType: 'routines',
  },
  {
    id: 'routine_50',
    name: 'Diamant',
    icon: '💎',
    description: '50 routines, tu es incroyable !',
    requirement: 50,
    requirementType: 'routines',
  },
  {
    id: 'routine_100',
    name: 'Invincible',
    icon: '🛡️',
    description: '100 routines completees, quelle endurance !',
    requirement: 100,
    requirementType: 'routines',
  },
  {
    id: 'routine_250',
    name: 'Maitre des routines',
    icon: '👑',
    description: '250 routines completees, tu es un vrai maitre !',
    requirement: 250,
    requirementType: 'routines',
  },
  {
    id: 'streak_3',
    name: 'En feu !',
    icon: '🔥',
    description: '3 jours de suite, bravo !',
    requirement: 3,
    requirementType: 'streak',
  },
  {
    id: 'streak_5',
    name: 'Regulier',
    icon: '📅',
    description: '5 jours de suite, tu tiens le rythme !',
    requirement: 5,
    requirementType: 'streak',
  },
  {
    id: 'streak_7',
    name: 'Fusee',
    icon: '🚀',
    description: '7 jours de suite !',
    requirement: 7,
    requirementType: 'streak',
  },
  {
    id: 'streak_14',
    name: 'Super regularite',
    icon: '💪',
    description: '14 jours de suite, impressionnant !',
    requirement: 14,
    requirementType: 'streak',
  },
  {
    id: 'streak_30',
    name: 'Legende',
    icon: '👑',
    description: '30 jours de suite, tu es une legende !',
    requirement: 30,
    requirementType: 'streak',
  },
  {
    id: 'streak_60',
    name: 'Imbattable',
    icon: '⚡',
    description: '60 jours de suite, personne ne te rattrape !',
    requirement: 60,
    requirementType: 'streak',
  },
  {
    id: 'streak_100',
    name: 'Mythique',
    icon: '🌠',
    description: '100 jours de suite, tu entres dans la legende !',
    requirement: 100,
    requirementType: 'streak',
  },
  {
    id: 'stars_1',
    name: 'Premiere etoile',
    icon: '⭐',
    description: 'Tu as gagne ta premiere etoile !',
    requirement: 1,
    requirementType: 'stars',
  },
  {
    id: 'stars_10',
    name: 'Petit collectionneur',
    icon: '✨',
    description: '10 etoiles collectees !',
    requirement: 10,
    requirementType: 'stars',
  },
  {
    id: 'stars_25',
    name: 'Chasseur d etoiles',
    icon: '🌟',
    description: '25 etoiles collectees, ca brille !',
    requirement: 25,
    requirementType: 'stars',
  },
  {
    id: 'stars_50',
    name: 'Brillant',
    icon: '💫',
    description: '50 etoiles collectees, quel eclat !',
    requirement: 50,
    requirementType: 'stars',
  },
  {
    id: 'stars_100',
    name: 'Collectionneur',
    icon: '🌠',
    description: '100 etoiles collectees !',
    requirement: 100,
    requirementType: 'stars',
  },
  {
    id: 'stars_250',
    name: 'Galaxie',
    icon: '🌌',
    description: '250 etoiles, tu as ta propre galaxie !',
    requirement: 250,
    requirementType: 'stars',
  },
  {
    id: 'stars_500',
    name: 'Univers',
    icon: '🪐',
    description: '500 etoiles, tu vis dans un univers de succes !',
    requirement: 500,
    requirementType: 'stars',
  },
];
