import { ChildMoodType } from '../types';

export type MoodPolarity = 'positive' | 'negative';

export interface MoodConfig {
  emoji: string;
  label: string;
  color: string;
  polarity: MoodPolarity;
  encouragements: string[];
  animationIntensity: 'calm' | 'normal' | 'energetic';
  /** Whether to auto-skip optional steps for this mood */
  skipOptional: boolean;
  /** Gradient colors for the run screen background */
  gradientColors: [string, string];
}

export const MOOD_CONFIG: Record<ChildMoodType, MoodConfig> = {
  // ---- Positive moods ----
  playful: {
    emoji: '🤪',
    label: 'Joueur',
    color: '#FF9F43',
    polarity: 'positive',
    encouragements: [
      'On part à l\'aventure !',
      'Mission en cours, prêt ?',
      'C\'est parti pour jouer !',
      'On fait ça en s\'amusant !',
      'Prêt pour le défi ?',
      'Une petite mission rigolote ?',
      'On commence le jeu !',
      'À toi de jouer !',
      'C\'est un niveau facile !',
      'On tente un combo ?',
      'On fait ça version fun !',
      'Hop, c\'est parti !',
      'Petit défi rigolo !',
      'On joue ensemble !',
      'À fond les manettes !',
      'C\'est un jeu d\'enfant !',
      'On lance la mission !',
      'On rigole et on avance !',
      'Mode joueur activé !',
      'Prêt à gagner ?',
      'Une étape = un point !',
      'On débloque le niveau suivant !',
      'Ça va être drôle !',
      'On fait ça en mode fun !',
      'Mission express !',
      'Petit challenge sympa !',
      'À toi le niveau suivant !',
      'On démarre le jeu !',
      'C\'est trop facile !',
      'On avance en s\'amusant !',
      'Allez, mini mission !',
      'Prêt à explorer ?',
      'On commence tranquille !',
      'On tente le bonus ?',
      'C\'est une aventure !',
      'À toi de gagner !',
      'On fait ça en mode cool !',
      'Défi accepté ?',
      'On avance en rigolant !',
      'C\'est un jeu rapide !',
      'Go mission !',
      'On part à l\'action !',
      'Petit jeu rapide !',
      'On s\'amuse un peu ?',
      'C\'est facile comme un jeu !',
      'Niveau 1, c\'est parti !',
      'Tu vas t\'amuser !',
      'Action !',
      'Let\'s go version fun !',
    ],
    animationIntensity: 'energetic',
    skipOptional: false,
    gradientColors: ['#FFF8F0', '#FFE0B2'],
  },
  happy: {
    emoji: '😊',
    label: 'Heureux',
    color: '#FFD93D',
    polarity: 'positive',
    encouragements: [
      'Tu es en pleine forme !',
      'On y va ensemble !',
      'Super énergie aujourd\'hui !',
      'Ça commence bien !',
      'Tu es prêt pour ça !',
      'Quelle belle énergie !',
      'On démarre avec le sourire !',
      'C\'est un bon moment !',
      'Tout roule !',
      'On continue comme ça !',
      'Tu es au top !',
      'C\'est agréable comme moment !',
      'On avance tranquillement !',
      'Belle journée en cours !',
      'On commence doucement !',
      'Tu es bien aujourd\'hui !',
      'C\'est parti sereinement !',
      'On y va calmement !',
      'Super état d\'esprit !',
      'Tu es prêt !',
      'On avance avec plaisir !',
      'C\'est fluide !',
      'On continue ensemble !',
      'Tout va bien !',
      'On garde ce rythme !',
      'Tu es dans un bon moment !',
      'On avance sans stress !',
      'C\'est simple aujourd\'hui !',
      'Tu es tranquille !',
      'On fait ça facilement !',
      'Tout est sous contrôle !',
      'On avance bien !',
      'C\'est un bon départ !',
      'Tu es serein !',
      'C\'est agréable !',
      'On reste calme !',
      'Tu es bien lancé !',
      'On progresse doucement !',
      'On fait ça ensemble !',
      'Belle énergie !',
      'On continue tranquille !',
      'Tout est ok !',
      'On avance sans pression !',
      'Tu es prêt pour la suite !',
      'On garde le sourire !',
      'Ça va bien se passer !',
      'On y va doucement !',
      'C\'est parfait comme ça !',
    ],
    animationIntensity: 'energetic',
    skipOptional: false,
    gradientColors: ['#FFF8F0', '#FFF9C4'],
  },
  motivated: {
    emoji: '💪',
    label: 'Motivé',
    color: '#00B894',
    polarity: 'positive',
    encouragements: [
      'Tu vas y arriver !',
      'C\'est parti !',
      'Tu es prêt !',
      'On avance !',
      'Tu gères !',
      'Continue comme ça !',
      'Tu es sur la bonne voie !',
      'On fonce !',
      'Rien ne t\'arrête !',
      'Tu es capable !',
      'On avance vite !',
      'C\'est facile pour toi !',
      'Tu assures !',
      'Tu progresses bien !',
      'Tu es concentré !',
      'On continue !',
      'Tu es fort !',
      'Tu peux le faire !',
      'On ne lâche rien !',
      'Tu es lancé !',
      'Encore un effort !',
      'Tu avances super bien !',
      'Tu es déterminé !',
      'Tu maîtrises !',
      'On continue sans pause !',
      'Tu es en forme !',
      'C\'est fluide !',
      'Tu avances vite !',
      'On garde le rythme !',
      'Tu es efficace !',
      'Tu es en contrôle !',
      'Tu progresses vite !',
      'On avance ensemble !',
      'Tu es prêt pour la suite !',
      'Tu es au top !',
      'Tu assures totalement !',
      'Tu es focus !',
      'On continue fort !',
      'Tu es solide !',
      'Rien ne bloque !',
      'Tu avances bien !',
      'Tu es en avance !',
      'Tu es rapide !',
      'On garde le cap !',
      'Tu es motivé !',
      'Tu es engagé !',
      'Tu es dans le flow !',
      'Tu vas réussir !',
    ],
    animationIntensity: 'energetic',
    skipOptional: false,
    gradientColors: ['#F0FFF4', '#C8E6C9'],
  },
  // ---- Negative moods ----
  sad: {
    emoji: '😢',
    label: 'Triste',
    color: '#74B9FF',
    polarity: 'negative',
    encouragements: [
      'Je suis avec toi.',
      'On y va doucement.',
      'Ce n\'est pas grave.',
      'On avance ensemble.',
      'Tu peux prendre ton temps.',
      'On fait juste un petit peu.',
      'Je reste avec toi.',
      'Tu n\'es pas seul.',
      'On commence doucement.',
      'C\'est ok comme tu te sens.',
      'On avance tranquillement.',
      'Tu peux y arriver.',
      'On fait petit à petit.',
      'Ce n\'est pas pressé.',
      'Tu peux essayer doucement.',
      'Je suis là.',
      'On commence quand tu veux.',
      'On fait une petite étape.',
      'Tu peux le faire.',
      'On avance calmement.',
      'C\'est ok d\'aller doucement.',
      'Tu fais de ton mieux.',
      'On reste tranquille.',
      'On avance sans stress.',
      'Tu es capable.',
      'On fait simple.',
      'On y va ensemble.',
      'Juste un petit pas.',
      'Tu peux essayer.',
      'On fait ça doucement.',
      'Ce n\'est pas grave si c\'est lent.',
      'On avance petit.',
      'Tu peux commencer doucement.',
      'Je t\'accompagne.',
      'On avance à ton rythme.',
      'C\'est bien comme ça.',
      'On fait un petit effort.',
      'On continue doucement.',
      'Tu es courageux.',
      'On reste calme.',
      'On fait ça tranquillement.',
      'Tu peux y arriver.',
      'Juste commencer suffit.',
      'Tu peux essayer doucement.',
      'On reste avec toi.',
      'On avance petit à petit.',
      'C\'est déjà très bien.',
    ],
    animationIntensity: 'calm',
    skipOptional: true,
    gradientColors: ['#F0F4FF', '#BBDEFB'],
  },
  angry: {
    emoji: '😡',
    label: 'En colère',
    color: '#FF6B6B',
    polarity: 'negative',
    encouragements: [
      'On respire doucement.',
      'On commence petit.',
      'Juste une étape.',
      'On y va calmement.',
      'On se pose un instant.',
      'Respire, puis on commence.',
      'On fait simple.',
      'On avance doucement.',
      'Juste un petit début.',
      'On reste calme.',
      'On commence tranquille.',
      'Une seule étape.',
      'On fait ça calmement.',
      'On avance sans se presser.',
      'On se calme un peu.',
      'Puis on commence.',
      'Juste essayer.',
      'On fait léger.',
      'On commence doucement.',
      'On avance petit.',
      'On respire encore.',
      'Puis on avance.',
      'Juste un petit pas.',
      'On reste tranquille.',
      'On avance doucement.',
      'Pas besoin de forcer.',
      'On commence calmement.',
      'Juste une action.',
      'On reste posé.',
      'On avance sans pression.',
      'On garde le calme.',
      'On fait petit.',
      'On respire puis on agit.',
      'Juste commencer.',
      'On fait au calme.',
      'On commence sans stress.',
      'Une étape suffit.',
      'On avance lentement.',
      'On reste calme ensemble.',
      'On fait ça tranquille.',
      'On respire puis on y va.',
      'Juste un début.',
      'On avance petit à petit.',
      'On reste posé.',
      'On commence doucement.',
      'On garde le calme.',
      'On avance sans pression.',
    ],
    animationIntensity: 'normal',
    skipOptional: true,
    gradientColors: ['#FFF0F0', '#FFCDD2'],
  },
  grumpy: {
    emoji: '😤',
    label: 'Grognon',
    color: '#A29BFE',
    polarity: 'negative',
    encouragements: [
      'On y va doucement.',
      'Une petite étape.',
      'Prends ton temps.',
      'Pas besoin d\'aller vite.',
      'On avance tranquillement.',
      'Juste une étape.',
      'On fait ça calmement.',
      'Tu peux y aller doucement.',
      'On prend son temps.',
      'C\'est ok d\'être lent.',
      'On commence petit.',
      'Juste un petit effort.',
      'On fait simple.',
      'Une chose à la fois.',
      'Pas de stress.',
      'On y va tranquille.',
      'Tu fais comme tu peux.',
      'C\'est suffisant.',
      'On avance doucement.',
      'Pas besoin de se presser.',
      'Juste un début.',
      'On commence tranquillement.',
      'Un petit pas suffit.',
      'On y va sans pression.',
      'Prends une pause si besoin.',
      'On reprend doucement.',
      'On reste calme.',
      'C\'est déjà bien.',
      'On fait simple aujourd\'hui.',
      'Un pas après l\'autre.',
      'C\'est facile.',
      'On ne force pas.',
      'On y va doucement ensemble.',
      'Juste commencer suffit.',
      'On avance petit à petit.',
      'On garde le rythme lent.',
      'Pas de pression.',
      'C\'est tranquille.',
      'Tu peux le faire doucement.',
      'Juste une action.',
      'On fait léger.',
      'On avance sans stress.',
      'C\'est ok comme ça.',
      'On fait au minimum.',
      'C\'est largement suffisant.',
      'Pas besoin d\'en faire plus.',
      'On y va petit.',
    ],
    animationIntensity: 'calm',
    skipOptional: true,
    gradientColors: ['#F5F0FF', '#D1C4E9'],
  },
};

export const POSITIVE_MOODS: ChildMoodType[] = ['playful', 'happy', 'motivated'];
export const NEGATIVE_MOODS: ChildMoodType[] = ['sad', 'angry', 'grumpy'];
export const MOOD_TYPES: ChildMoodType[] = [...POSITIVE_MOODS, ...NEGATIVE_MOODS];

/** Check if a mood is negative */
export function isNegativeMood(mood: ChildMoodType): boolean {
  return MOOD_CONFIG[mood].polarity === 'negative';
}
