export type StepCatalogCategoryId =
  | 'hygiene'
  | 'habillage'
  | 'repas'
  | 'sortie'
  | 'maison'
  | 'calme'
  | 'emotions';

export interface StepCatalogCategory {
  id: StepCatalogCategoryId;
  label: string;
  icon: string;
}

export interface StepCatalogItem {
  id: string;
  title: string;
  icon: string;
  durationMinutes: number;
  minimumDurationMinutes?: number;
  instruction: string;
  isRequired: boolean;
  categoryId: StepCatalogCategoryId;
}

const sec = (value: number) => value / 60;

function item(
  id: string,
  title: string,
  icon: string,
  durationMinutes: number,
  minimumDurationMinutes: number,
  instruction: string,
  isRequired: boolean,
  categoryId: StepCatalogCategoryId,
): StepCatalogItem {
  return {
    id,
    title,
    icon,
    durationMinutes,
    minimumDurationMinutes,
    instruction,
    isRequired,
    categoryId,
  };
}

export const STEP_CATALOG_CATEGORIES: StepCatalogCategory[] = [
  { id: 'hygiene', label: 'Hygiène', icon: '🧼' },
  { id: 'habillage', label: 'Habillage', icon: '👕' },
  { id: 'repas', label: 'Repas', icon: '🍽️' },
  { id: 'sortie', label: 'Sortie', icon: '🎒' },
  { id: 'maison', label: 'Maison', icon: '🧹' },
  { id: 'calme', label: 'Calme', icon: '🌙' },
  { id: 'emotions', label: 'Émotions', icon: '❤️' },
];

export const STEP_CATALOG_ITEMS: StepCatalogItem[] = [
  item(
    'step-toilettes',
    'Je vais aux toilettes',
    '🚽',
    2,
    1,
    'Je prends mon temps puis je pense à tirer la chasse.',
    true,
    'hygiene',
  ),
  item(
    'step-lave-visage',
    'Je me lave le visage',
    '💦',
    2,
    1,
    'Je mouille, je frotte, puis je m’essuie.',
    true,
    'hygiene',
  ),
  item(
    'step-brosse-dents',
    'Je me brosse les dents',
    '🪥',
    2,
    1,
    'Je brosse devant, derrière, en haut et en bas.',
    true,
    'hygiene',
  ),
  item(
    'step-lave-mains',
    'Je me lave les mains',
    '🧼',
    2,
    1,
    'Je mets du savon, je frotte bien puis je rince.',
    true,
    'hygiene',
  ),
  item(
    'step-messuie',
    'Je m’essuie',
    '🧻',
    1,
    sec(30),
    'Je m’essuie correctement avant de sortir.',
    true,
    'hygiene',
  ),
  item(
    'step-tire-chasse',
    'Je tire la chasse',
    '🚿',
    sec(10),
    sec(5),
    'Je vérifie que tout est propre après mon passage.',
    true,
    'hygiene',
  ),
  item(
    'step-habille',
    'Je m’habille',
    '👕',
    5,
    3,
    'Je mets mes vêtements dans le bon ordre.',
    true,
    'habillage',
  ),
  item(
    'step-pyjama',
    'Je mets mon pyjama',
    '👕',
    3,
    2,
    'Je choisis mon pyjama puis je l’enfile calmement.',
    true,
    'habillage',
  ),
  item(
    'step-chaussettes',
    'Je mets mes chaussettes',
    '🧦',
    2,
    1,
    'Je vérifie que mes chaussettes sont dans le bon sens.',
    true,
    'habillage',
  ),
  item(
    'step-chaussures',
    'Je mets mes chaussures',
    '👟',
    2,
    1,
    'Je mets chaque chaussure au bon pied.',
    true,
    'habillage',
  ),
  item(
    'step-manteau',
    'Je prends mon manteau',
    '🧥',
    1,
    sec(30),
    'Je prends mon manteau avant de sortir.',
    true,
    'habillage',
  ),
  item(
    'step-bonnet',
    'Je mets mon bonnet',
    '🧢',
    sec(30),
    sec(10),
    'Je me couvre bien s’il fait froid.',
    false,
    'habillage',
  ),
  item(
    'step-petit-dejeuner',
    'Je prends mon petit-déjeuner',
    '🥣',
    10,
    5,
    'Je prends le temps de bien manger avant de partir.',
    true,
    'repas',
  ),
  item(
    'step-assois-table',
    'Je m’assois à table',
    '🪑',
    sec(30),
    sec(10),
    'Je m’installe calmement à ma place.',
    true,
    'repas',
  ),
  item(
    'step-serviette',
    'Je mets ma serviette',
    '🧻',
    sec(30),
    sec(10),
    'Je protège mes vêtements avant le repas.',
    true,
    'repas',
  ),
  item(
    'step-pret-manger',
    'Je suis prêt à manger',
    '🍽️',
    sec(10),
    sec(5),
    'Je suis bien installé et je peux commencer.',
    true,
    'repas',
  ),
  item(
    'step-apporte-assiette',
    'J’apporte mon assiette',
    '🍽️',
    1,
    sec(30),
    'J’aide à ranger la table à la fin du repas.',
    false,
    'repas',
  ),
  item(
    'step-sac',
    'Je prends mon sac',
    '🎒',
    sec(30),
    sec(10),
    'Je vérifie que mon sac est prêt avant de partir.',
    true,
    'sortie',
  ),
  item(
    'step-gourde',
    'Je vérifie ma gourde',
    '🧴',
    sec(30),
    sec(10),
    'Je regarde si ma gourde est bien dans mon sac.',
    true,
    'sortie',
  ),
  item(
    'step-au-revoir',
    'Je dis au revoir',
    '👋',
    sec(30),
    sec(10),
    'Je dis au revoir avant de partir.',
    false,
    'sortie',
  ),
  item(
    'step-pose-affaires',
    'Je pose mes affaires',
    '🎒',
    1,
    sec(30),
    'Je pose mon sac et mes objets au bon endroit.',
    true,
    'sortie',
  ),
  item(
    'step-enleve-chaussures',
    'J’enlève mes chaussures',
    '👟',
    1,
    sec(30),
    'Je retire mes chaussures en rentrant.',
    true,
    'sortie',
  ),
  item(
    'step-range-jouets',
    'Je range mes jouets',
    '🧸',
    5,
    2,
    'Chaque jouet retourne à sa place.',
    true,
    'maison',
  ),
  item(
    'step-ramasse-objets',
    'Je ramasse les objets',
    '📦',
    2,
    1,
    'Je commence par ce qui traîne autour de moi.',
    true,
    'maison',
  ),
  item(
    'step-remets-place',
    'Je remets à leur place',
    '📦',
    3,
    2,
    'Je replace chaque objet au bon endroit.',
    true,
    'maison',
  ),
  item(
    'step-fais-mon-lit',
    'Je fais mon lit',
    '🛏️',
    3,
    1,
    'Je lisse ma couette et je replace mon oreiller.',
    false,
    'maison',
  ),
  item(
    'step-respire-doucement',
    'Je respire doucement',
    '🌬️',
    1,
    sec(30),
    'J’inspire et j’expire lentement.',
    false,
    'calme',
  ),
  item(
    'step-massois-calme',
    'Je m’assois calmement',
    '🪑',
    1,
    sec(30),
    'Je prends un moment pour m’installer.',
    true,
    'calme',
  ),
  item(
    'step-regarde-livre',
    'Je regarde un livre',
    '📖',
    5,
    2,
    'Je choisis un livre et je prends un temps calme.',
    false,
    'calme',
  ),
  item(
    'step-prends-doudou',
    'Je prends mon doudou',
    '🧸',
    sec(30),
    sec(10),
    'Je prends mon objet rassurant si j’en ai besoin.',
    false,
    'calme',
  ),
  item(
    'step-ecoute-histoire',
    'J’écoute une histoire',
    '📖',
    5,
    3,
    'Une histoire courte pour se poser ou s’endormir.',
    false,
    'calme',
  ),
  item(
    'step-dis-emotion',
    'Je dis ce que je ressens',
    '🗣️',
    1,
    sec(30),
    'Je mets des mots simples sur mon émotion.',
    false,
    'emotions',
  ),
  item(
    'step-fais-pause',
    'Je fais une pause',
    '✋',
    1,
    sec(30),
    'Je m’arrête un instant avant de continuer.',
    false,
    'emotions',
  ),
  item(
    'step-demande-aide',
    'Je demande de l’aide',
    '🙋',
    sec(30),
    sec(10),
    'Je ne reste pas seul quand c’est difficile.',
    false,
    'emotions',
  ),
  item(
    'step-dis-pardon',
    'Je dis pardon',
    '🙏',
    sec(30),
    sec(10),
    'Je répare doucement après un conflit.',
    false,
    'emotions',
  ),
];
