import { Activity, ActivityType, DevelopmentGoal, IndependenceLevel, NoiseLevel, ParentMood, Season } from "./types";

type ActivityMetadata = Pick<
  Activity,
  | "thumbnail"
  | "image"
  | "setupTime"
  | "cleanupTime"
  | "independenceLevel"
  | "noiseLevel"
  | "requiresSupervision"
  | "screenFree"
  | "groupActivity"
  | "playerCountMin"
  | "playerCountMax"
  | "activityType"
  | "developmentGoals"
  | "season"
  | "parentMood"
  | "source"
>;

type BaseActivity = Omit<Activity, keyof ActivityMetadata> & Partial<ActivityMetadata>;

const baseActivities: BaseActivity[] = [
  {
    id: "radio-famille",
    title: "Radio Famille",
    thumbnail: "📻",
    ageMin: 5,
    ageMax: 10,
    duration: 25,
    setupTime: 2,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    groupActivity: true,
    playerCountMin: 2,
    playerCountMax: 6,
    activityType: "social",
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["langage", "imagination", "social"],
    developmentGoals: ["expression-orale", "cooperation"],
    description: "Creer une emission de radio imaginaire.",
    steps: [
      "Choisissez un theme.",
      "Un enfant devient animateur.",
      "Les autres inventent des chroniques ou interviews.",
      "Ajoutez une meteo ou publicite absurde."
    ],
    koVariant: "Faire seulement une mini interview.",
    harderVariant: "Creer une vraie emission de 10 minutes."
  },
  {
  id: "keepy-uppy",
  title: "Keepy Uppy",
  thumbnail: "🎈",
  ageMin: 2,
  ageMax: 10,
  duration: 15,
  setupTime: 1,
  cleanupTime: 0,
  independenceLevel: "medium",
  noiseLevel: "medium",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 1,
  playerCountMax: 8,
  activityType: "challenge",
  parentMood: ["besoin-defoulement", "patient"],
  parentEnergy: "medium",
  weather: "indoor",
  messLevel: "low",
  materials: ["ballon"],
  skills: ["motricite", "cooperation"],
  developmentGoals: ["coordination", "reaction"],
  description: "Garder un ballon en l'air le plus longtemps possible.",
  steps: [
    "Lancez doucement le ballon.",
    "Chacun doit l'empecher de toucher le sol.",
    "Comptez les touches.",
    "Ajoutez des regles rigolotes."
  ],
  koVariant: "Jouer assis.",
  harderVariant: "Ajouter plusieurs ballons."
},
{
  id: "statues-musicales-bluey",
  title: "Statues musicales",
  thumbnail: "🕺",
  ageMin: 2,
  ageMax: 10,
  duration: 10,
  setupTime: 0,
  cleanupTime: 0,
  independenceLevel: "medium",
  noiseLevel: "high",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 2,
  playerCountMax: 10,
  activityType: "challenge",
  parentMood: ["besoin-defoulement"],
  parentEnergy: "medium",
  weather: "any",
  messLevel: "low",
  materials: [],
  skills: ["motricite", "concentration"],
  developmentGoals: ["self-control"],
  description: "Danser puis se figer instantanement.",
  steps: [
    "Lance une musique ou chante.",
    "Tout le monde danse.",
    "Quand la musique s'arrete, tout le monde se fige.",
    "Ajoutez des poses absurdes."
  ],
  koVariant: "Faire des pauses tres courtes.",
  harderVariant: "Interdiction de rire."
},
{
  id: "xylophone-magique",
  title: "Xylophone magique",
  thumbnail: "✨",
  ageMin: 3,
  ageMax: 8,
  duration: 15,
  setupTime: 1,
  cleanupTime: 0,
  independenceLevel: "medium",
  noiseLevel: "medium",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 2,
  playerCountMax: 6,
  activityType: "story",
  parentMood: ["patient"],
  parentEnergy: "ko",
  weather: "any",
  messLevel: "low",
  materials: [],
  skills: ["imagination", "social"],
  developmentGoals: ["jeu-symbolique"],
  description: "Faire semblant de figer les autres avec un objet magique.",
  steps: [
    "Choisissez un objet magique.",
    "Une personne touche quelqu'un.",
    "La personne doit rester figee.",
    "Une autre personne peut la liberer."
  ],
  koVariant: "Faire des freezes tres courts.",
  harderVariant: "Ajouter missions et personnages."
},
{
  id: "hotel-imaginaire",
  title: "Hotel imaginaire",
  thumbnail: "🏨",
  ageMin: 3,
  ageMax: 10,
  duration: 30,
  setupTime: 3,
  cleanupTime: 2,
  independenceLevel: "high",
  noiseLevel: "medium",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 2,
  playerCountMax: 8,
  activityType: "social",
  parentMood: ["patient"],
  parentEnergy: "medium",
  weather: "indoor",
  messLevel: "medium",
  materials: ["coussins", "doudous"],
  skills: ["langage", "imagination", "social"],
  developmentGoals: ["cooperation"],
  description: "Transformer le salon en hotel complet.",
  steps: [
    "Construisez une reception.",
    "Attribuez les roles.",
    "Accueillez les clients.",
    "Inventez des problemes absurdes."
  ],
  koVariant: "Faire seulement la reception.",
  harderVariant: "Ajouter restaurant et spa."
},
{
  id: "grannies",
  title: "Mamies rigolotes",
  thumbnail: "👵",
  ageMin: 4,
  ageMax: 10,
  duration: 20,
  setupTime: 2,
  cleanupTime: 1,
  independenceLevel: "high",
  noiseLevel: "high",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 2,
  playerCountMax: 6,
  activityType: "story",
  parentMood: ["patient"],
  parentEnergy: "medium",
  weather: "any",
  messLevel: "low",
  materials: ["doudous"],
  skills: ["imagination", "social", "langage"],
  developmentGoals: ["expression"],
  description: "Faire semblant d'etre des mamies excentriques.",
  steps: [
    "Choisissez des noms de mamies.",
    "Marchez tres lentement.",
    "Inventez des courses absurdes.",
    "Parlez avec des voix rigolotes."
  ],
  koVariant: "Faire juste une promenade.",
  harderVariant: "Ajouter un magasin imaginaire."
},
{
  id: "floor-is-lava",
  title: "Le sol est de la lave",
  thumbnail: "🌋",
  ageMin: 3,
  ageMax: 12,
  duration: 15,
  setupTime: 2,
  cleanupTime: 1,
  independenceLevel: "medium",
  noiseLevel: "high",
  requiresSupervision: true,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 1,
  playerCountMax: 8,
  activityType: "motor",
  parentMood: ["besoin-defoulement"],
  parentEnergy: "motivated",
  weather: "indoor",
  messLevel: "medium",
  materials: ["coussins"],
  skills: ["motricite", "equilibre"],
  developmentGoals: ["coordination"],
  description: "Traverser la piece sans toucher la lave.",
  steps: [
    "Dispose des coussins.",
    "Le sol devient de la lave.",
    "Traverse sans tomber.",
    "Ajoute des obstacles."
  ],
  koVariant: "Petit parcours.",
  harderVariant: "Transporter un objet fragile."
},
{
  id: "livraison-dance-mode",
  title: "Livraison danse",
  thumbnail: "📦",
  ageMin: 4,
  ageMax: 10,
  duration: 15,
  setupTime: 1,
  cleanupTime: 1,
  independenceLevel: "medium",
  noiseLevel: "high",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 2,
  playerCountMax: 8,
  activityType: "challenge",
  parentMood: ["besoin-defoulement"],
  parentEnergy: "medium",
  weather: "any",
  messLevel: "low",
  materials: ["cartons"],
  skills: ["motricite", "social"],
  developmentGoals: ["coordination"],
  description: "Livrer des colis uniquement en dansant.",
  steps: [
    "Prepare quelques colis imaginaires.",
    "Chaque livraison doit etre danse.",
    "Inventez des styles ridicules.",
    "Changez de musique imaginaire."
  ],
  koVariant: "Faire une seule livraison.",
  harderVariant: "Ajouter obstacles et chronometre."
},
{
  id: "mini-marionnettes",
  title: "Mini Marionnettes",
  thumbnail: "🎭",
  ageMin: 3,
  ageMax: 10,
  duration: 20,
  setupTime: 2,
  cleanupTime: 1,
  independenceLevel: "high",
  noiseLevel: "medium",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 1,
  playerCountMax: 6,
  activityType: "creative",
  parentMood: ["patient"],
  parentEnergy: "ko",
  weather: "any",
  messLevel: "low",
  materials: ["chaussettes"],
  skills: ["imagination", "langage"],
  developmentGoals: ["narration"],
  description: "Creer un mini spectacle de marionnettes.",
  steps: [
    "Choisissez des personnages.",
    "Inventez un probleme.",
    "Faites parler les marionnettes.",
    "Terminez par une solution absurde."
  ],
  koVariant: "Faire une scene tres courte.",
  harderVariant: "Ajouter decor et musique."
},
{
  id: "dance-mode",
  title: "Mode Danse",
  thumbnail: "💃",
  ageMin: 3,
  ageMax: 12,
  duration: 10,
  setupTime: 0,
  cleanupTime: 0,
  independenceLevel: "medium",
  noiseLevel: "high",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 1,
  playerCountMax: 10,
  activityType: "social",
  parentMood: ["besoin-defoulement"],
  parentEnergy: "medium",
  weather: "any",
  messLevel: "low",
  materials: [],
  skills: ["motricite", "social"],
  developmentGoals: ["expression-corporelle"],
  description: "Tout mouvement devient une danse.",
  steps: [
    "Annoncez Dance Mode.",
    "Chaque action devient danse.",
    "Marchez, rangez ou sautez en rythme.",
    "Ajoutez des poses ridicules."
  ],
  koVariant: "Danser assis.",
  harderVariant: "Faire une choregraphie complete."
},
{
  id: "marchand-glaces",
  title: "Marchand de glaces",
  thumbnail: "🍦",
  ageMin: 3,
  ageMax: 9,
  duration: 20,
  setupTime: 2,
  cleanupTime: 1,
  independenceLevel: "high",
  noiseLevel: "medium",
  requiresSupervision: false,
  screenFree: true,
  groupActivity: true,
  playerCountMin: 2,
  playerCountMax: 6,
  activityType: "social",
  parentMood: ["patient"],
  parentEnergy: "ko",
  weather: "outdoor",
  messLevel: "low",
  materials: ["bols", "cuillere"],
  skills: ["langage", "imagination"],
  developmentGoals: ["socialisation"],
  description: "Ouvrir un marchand de glaces imaginaire.",
  steps: [
    "Preparez les parfums imaginaires.",
    "Les clients commandent.",
    "Le vendeur prepare les glaces.",
    "Ajoutez des parfums absurdes."
  ],
  koVariant: "Faire seulement deux parfums.",
  harderVariant: "Ajouter monnaie et menu."
},
  {
    id: "escape-room-salon",
    title: "Escape Room Salon",
    thumbnail: "🔐",
    ageMin: 6,
    ageMax: 12,
    duration: 30,
    setupTime: 10,
    cleanupTime: 5,
    independenceLevel: "low",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    groupActivity: true,
    playerCountMin: 2,
    playerCountMax: 5,
    activityType: "investigation",
    parentMood: ["patient"],
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["cartons", "feuilles", "crayons"],
    skills: ["concentration", "logique", "cooperation"],
    developmentGoals: ["resolution-problemes", "cooperation"],
    description: "Resoudre des enigmes simples pour retrouver un tresor.",
    steps: [
      "Cache un objet tresor.",
      "Prepare quelques indices.",
      "Les enfants resolvent les enigmes.",
      "Le tresor est retrouve."
    ],
    koVariant: "Faire seulement deux indices.",
    harderVariant: "Ajouter faux indices et cadenas symboliques."
  },
  {
    id: "tribunal-doudous",
    title: "Tribunal des Doudous",
    thumbnail: "⚖️",
    ageMin: 5,
    ageMax: 10,
    duration: 20,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    groupActivity: true,
    playerCountMin: 2,
    playerCountMax: 6,
    activityType: "story",
    parentMood: ["patient"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous"],
    skills: ["langage", "imagination", "social"],
    developmentGoals: ["argumentation", "expression-orale"],
    description: "Un doudou est accuse d'un crime imaginaire ridicule.",
    steps: [
      "Choisissez le doudou accuse.",
      "Inventez l'accusation.",
      "Chacun defend ou accuse.",
      "Votez pour le verdict."
    ],
    koVariant: "Faire un proces tres court.",
    harderVariant: "Ajouter temoins et preuves."
  },
  {
    id: "olympiades-salon",
    title: "Olympiades du Salon",
    thumbnail: "🏅",
    ageMin: 4,
    ageMax: 12,
    duration: 30,
    setupTime: 5,
    cleanupTime: 5,
    independenceLevel: "medium",
    noiseLevel: "high",
    requiresSupervision: true,
    screenFree: true,
    groupActivity: true,
    playerCountMin: 2,
    playerCountMax: 8,
    activityType: "challenge",
    parentMood: ["besoin-defoulement"],
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["chaussettes", "coussins", "bols"],
    skills: ["motricite", "social"],
    developmentGoals: ["cooperation", "coordination"],
    description: "Creer plusieurs mini defis sportifs a la maison.",
    steps: [
      "Prepare plusieurs ateliers.",
      "Faites les defis chacun votre tour.",
      "Comptez les points ou inventez des recompenses.",
      "Terminez par une danse des champions."
    ],
    koVariant: "Faire seulement deux epreuves.",
    harderVariant: "Ajouter equipes et chrono."
  },
  {
    id: "ville-futur",
    title: "Ville du Futur",
    thumbnail: "🏙️",
    ageMin: 6,
    ageMax: 12,
    duration: 45,
    setupTime: 5,
    cleanupTime: 5,
    independenceLevel: "high",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    groupActivity: true,
    playerCountMin: 1,
    playerCountMax: 6,
    activityType: "construction",
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["cartons", "feuilles", "crayons"],
    skills: ["imagination", "construction"],
    developmentGoals: ["creativite", "projection"],
    description: "Inventer une ville du futur avec ses regles et batiments.",
    steps: [
      "Construisez des batiments.",
      "Inventez des transports.",
      "Choisissez les regles de la ville.",
      "Presentez votre monde."
    ],
    koVariant: "Creer seulement un quartier.",
    harderVariant: "Ajouter cartes et habitants."
  },
  {
    id: "mission-agent-secret",
    title: "Mission Agent Secret",
    thumbnail: "🕵️",
    ageMin: 5,
    ageMax: 12,
    duration: 25,
    setupTime: 5,
    cleanupTime: 2,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    groupActivity: true,
    playerCountMin: 1,
    playerCountMax: 5,
    activityType: "investigation",
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "any",
    messLevel: "low",
    materials: ["feuilles", "crayons"],
    skills: ["logique", "motricite"],
    developmentGoals: ["observation"],
    description: "Realiser des missions secretes dans la maison ou dehors.",
    steps: [
      "Prepare une mission.",
      "Cache des indices.",
      "L'agent resout les etapes.",
      "Mission accomplie."
    ],
    koVariant: "Faire une seule mission.",
    harderVariant: "Ajouter code secret et chronometre."
  },
  {
    id: "mission-chaussettes",
    title: "Mission chaussettes",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["chaussettes"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Transformer les chaussettes en petites missions faciles.",
    steps: [
      "Pose quelques chaussettes propres au sol.",
      "Demande a l'enfant de les regrouper par couleur ou par paire.",
      "Propose de lancer doucement les boules dans un panier imaginaire.",
      "Finis par une mission rangement dans le tiroir."
    ],
    koVariant: "Reste assis et annonce les couleurs a chercher.",
    harderVariant: "Ajoute un chrono doux ou demande un tri par taille."
  },
  {
    id: "restaurant-doudous",
    title: "Restaurant des doudous",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous", "bols", "cuillere"],
    skills: ["langage", "imagination", "autonomie"],
    description: "Les doudous passent commande et l'enfant prepare le service.",
    steps: [
      "Installe deux ou trois doudous autour d'un bol.",
      "Demande ce que chaque doudou veut manger.",
      "L'enfant sert avec la cuillere et invente les plats.",
      "Chaque doudou dit merci avec une voix differente."
    ],
    koVariant: "Fais seulement la voix du client depuis le canape.",
    harderVariant: "Ajoute des menus dessines sur une feuille."
  },
  {
    id: "parcours-ninja-salon",
    title: "Parcours ninja du salon",
    ageMin: 3,
    ageMax: 6,
    duration: 15,
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["coussins"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Un petit parcours moteur avec les coussins du salon.",
    steps: [
      "Aligne des coussins avec un peu d'espace.",
      "Montre le trajet: marcher, sauter, contourner.",
      "L'enfant traverse sans toucher le sol imaginaire.",
      "Change une regle a chaque passage."
    ],
    koVariant: "Fais un parcours tres court avec deux coussins.",
    harderVariant: "Ajoute une consigne: marcher comme un chat ou a reculons."
  },
  {
    id: "chasse-couleurs",
    title: "Chasse aux couleurs",
    ageMin: 1,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["langage", "concentration", "autonomie"],
    description: "Trouver des objets d'une couleur dans la maison.",
    steps: [
      "Choisis une couleur simple.",
      "Demande a l'enfant de trouver un objet de cette couleur.",
      "Nomme l'objet ensemble.",
      "Change de couleur quand l'envie baisse."
    ],
    koVariant: "Demande de pointer les objets sans se deplacer.",
    harderVariant: "Cherche deux objets par couleur ou invente une phrase avec chacun."
  },
  {
    id: "bain-animaux",
    title: "Bain des animaux",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "rainy",
    messLevel: "medium",
    materials: ["eau", "bols", "figurines"],
    skills: ["motricite", "imagination", "autonomie"],
    description: "Laver les figurines dans un petit bol d'eau.",
    steps: [
      "Remplis un bol avec un fond d'eau.",
      "Place quelques figurines a cote.",
      "L'enfant les lave une par une avec ses mains.",
      "Installe les figurines propres sur une serviette."
    ],
    koVariant: "Limite l'eau a un tout petit fond dans un bol stable.",
    harderVariant: "Trie les animaux propres par taille ou par famille."
  },
  {
    id: "boite-mystere",
    title: "Boite mystere",
    ageMin: 3,
    ageMax: 6,
    duration: 10,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["cartons", "doudous", "voitures"],
    skills: ["langage", "concentration", "imagination"],
    description: "Deviner un objet cache dans une boite.",
    steps: [
      "Cache un objet dans un petit carton.",
      "L'enfant touche sans regarder.",
      "Pose des questions: c'est doux, dur, petit ?",
      "Il annonce son idee puis verifie."
    ],
    koVariant: "Cache seulement deux objets tres differents.",
    harderVariant: "Demande a l'enfant de cacher un objet pour toi."
  },
  {
    id: "parking-geant",
    title: "Parking geant",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["voitures", "feuilles", "crayons"],
    skills: ["motricite", "concentration", "imagination"],
    description: "Dessiner des places et garer les voitures.",
    steps: [
      "Trace quelques rectangles sur une feuille.",
      "Donne une voiture a garer.",
      "Ajoute des places pour les grandes et petites voitures.",
      "Fais sortir les voitures une par une."
    ],
    koVariant: "Dessine trois places seulement.",
    harderVariant: "Ajoute des numeros et demande de garer dans l'ordre."
  },
  {
    id: "yoga-rigolo",
    title: "Yoga rigolo",
    ageMin: 2,
    ageMax: 6,
    duration: 5,
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "emotions", "concentration"],
    description: "Quelques postures simples pour souffler ensemble.",
    steps: [
      "Choisis un animal: chat, grenouille ou etoile.",
      "Montre une posture tres simple.",
      "Respirez trois fois doucement.",
      "Changez d'animal si l'enfant veut continuer."
    ],
    koVariant: "Fais seulement la respiration et les noms d'animaux.",
    harderVariant: "Inventez une mini histoire avec trois postures."
  },
  {
    id: "courrier-secret",
    title: "Courrier secret",
    ageMin: 3,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["feuilles", "crayons", "scotch"],
    skills: ["langage", "imagination", "motricite"],
    description: "Preparer des petits courriers pour la maison.",
    steps: [
      "Plie une feuille en petit message.",
      "L'enfant dessine ou dicte un mot.",
      "Fermez le courrier avec un bout de scotch.",
      "Livrez-le a un doudou, une porte ou un parent."
    ],
    koVariant: "L'enfant dessine, tu ecris un seul mot.",
    harderVariant: "Ajoute une adresse et un plan de livraison."
  },
  {
    id: "transvasement-baignoire",
    title: "Transvasement dans la baignoire",
    ageMin: 1,
    ageMax: 4,
    duration: 15,
    parentEnergy: "medium",
    weather: "rainy",
    messLevel: "medium",
    materials: ["eau", "bols", "cuillere"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Verser, remplir et vider avec peu d'eau.",
    steps: [
      "Installe deux bols dans la baignoire ou la douche.",
      "Mets un petit fond d'eau.",
      "L'enfant deplace l'eau avec la cuillere.",
      "Ajoute un defi: remplir le bol jusqu'au trait imaginaire."
    ],
    koVariant: "Assieds-toi a cote et limite a deux recipients.",
    harderVariant: "Ajoute trois tailles de recipients a comparer."
  },
  {
    id: "cuisine-imaginaire",
    title: "Cuisine imaginaire",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["bols", "cuillere", "pates"],
    skills: ["imagination", "langage", "motricite"],
    description: "Inventer une recette sans cuisson.",
    steps: [
      "Verse quelques pates seches dans un bol.",
      "L'enfant melange avec la cuillere.",
      "Demande le nom de la recette.",
      "Servez le plat imaginaire a un doudou."
    ],
    koVariant: "Utilise un seul bol et tres peu de pates.",
    harderVariant: "Ajoute une commande precise: soupe, gateau ou salade."
  },
  {
    id: "theatre-emotions",
    title: "Theatre des emotions",
    ageMin: 3,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous"],
    skills: ["emotions", "langage", "imagination"],
    description: "Les doudous jouent la joie, la peur ou la colere.",
    steps: [
      "Choisis un doudou acteur.",
      "Annonce une emotion simple.",
      "Fais une mini scene avec une voix courte.",
      "L'enfant devine ou rejoue l'emotion."
    ],
    koVariant: "Fais seulement des visages et laisse l'enfant deviner.",
    harderVariant: "Demande une solution pour aider le doudou."
  },
  {
    id: "course-glacons",
    title: "Course des glacons",
    ageMin: 3,
    ageMax: 6,
    duration: 10,
    parentEnergy: "motivated",
    weather: "outdoor",
    messLevel: "medium",
    materials: ["eau", "cuillere", "bols"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Transporter un glacon ou un peu d'eau sans renverser.",
    steps: [
      "Place un bol depart et un bol arrivee.",
      "Donne une cuillere a l'enfant.",
      "Il transporte un glacon ou un peu d'eau.",
      "Comptez les trajets reussis."
    ],
    koVariant: "Fais-le dans la baignoire avec de l'eau seulement.",
    harderVariant: "Allonge le trajet ou ajoute un virage."
  },
  {
    id: "sauvetage-jouets",
    title: "Sauvetage des jouets",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["scotch", "voitures", "figurines"],
    skills: ["motricite", "concentration", "imagination"],
    description: "Liberer des jouets bloques par quelques bandes de scotch.",
    steps: [
      "Colle doucement une voiture ou figurine sur une feuille ou un carton.",
      "Explique que le jouet est bloque.",
      "L'enfant retire le scotch avec les doigts.",
      "Chaque jouet sauve rejoint la zone securite."
    ],
    koVariant: "Utilise un seul morceau de scotch facile a retirer.",
    harderVariant: "Ajoute une histoire avec plusieurs secours a organiser."
  },
  {
    id: "tri-pinces-linge",
    title: "Tri des pinces a linge",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["pinces a linge", "bols"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Trier, pincer et deplacer les pinces a linge.",
    steps: [
      "Pose des pinces a linge dans un bol.",
      "L'enfant les deplace vers un autre bol.",
      "Montre comment pincer le bord du bol.",
      "Comptez les pinces accrochees."
    ],
    koVariant: "Demande seulement de remplir et vider les bols.",
    harderVariant: "Trie par couleur ou fais une suite de motifs."
  },
  {
    id: "cabane-express",
    title: "Cabane express",
    ageMin: 2,
    ageMax: 6,
    duration: 30,
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["coussins", "doudous", "livres"],
    skills: ["imagination", "autonomie", "emotions"],
    description: "Construire un petit coin calme et habite.",
    steps: [
      "Regroupe deux ou trois coussins.",
      "Installe un doudou gardien.",
      "Ajoute un livre pour le coin calme.",
      "L'enfant choisit ce qui se passe dans la cabane."
    ],
    koVariant: "Fais juste un nid avec deux coussins.",
    harderVariant: "Ajoute une entree, une sortie et une mission de cabane."
  },
  {
    id: "cherche-trouve-maison",
    title: "Cherche et trouve maison",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: [],
    skills: ["langage", "concentration", "autonomie"],
    description: "Observer la piece et trouver des objets connus.",
    steps: [
      "Choisis une piece depuis un endroit confortable.",
      "Demande: trouve quelque chose de rond.",
      "L'enfant pointe ou rapporte l'objet.",
      "Continue avec doux, petit, rouge ou bruyant."
    ],
    koVariant: "L'enfant pointe seulement, sans rapporter.",
    harderVariant: "Donne deux criteres: petit et bleu, doux et rond."
  },
  {
    id: "peche-bouchons",
    title: "Peche aux bouchons",
    ageMin: 2,
    ageMax: 5,
    duration: 15,
    parentEnergy: "medium",
    weather: "rainy",
    messLevel: "medium",
    materials: ["eau", "bols", "cuillere"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Attraper de petits objets flottants avec une cuillere.",
    steps: [
      "Mets un fond d'eau dans un bol large.",
      "Ajoute de petits objets flottants propres si tu en as.",
      "L'enfant les attrape avec la cuillere.",
      "Il les depose dans un bol sec."
    ],
    koVariant: "Remplace les objets par une seule cuillere a remplir d'eau.",
    harderVariant: "Compte les prises ou trie par taille."
  },
  {
    id: "tour-coussins",
    title: "Tour de coussins",
    ageMin: 1,
    ageMax: 4,
    duration: 10,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["coussins"],
    skills: ["motricite", "concentration", "emotions"],
    description: "Empiler et faire tomber une tour douce.",
    steps: [
      "Pose un coussin au sol.",
      "Ajoutez les coussins un par un.",
      "Comptez la hauteur ensemble.",
      "L'enfant fait tomber la tour en douceur."
    ],
    koVariant: "Fais une mini tour avec deux coussins.",
    harderVariant: "Demande une tour qui tient cinq secondes."
  },
  {
    id: "mini-chasse-tresor",
    title: "Mini chasse au tresor",
    ageMin: 3,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "any",
    messLevel: "low",
    materials: ["doudous", "feuilles", "crayons"],
    skills: ["imagination", "concentration", "langage"],
    description: "Suivre des indices tres simples jusqu'au tresor.",
    steps: [
      "Cache un doudou tresor dans une piece.",
      "Dessine un indice simple sur une feuille.",
      "L'enfant suit l'indice et cherche.",
      "Celebre la trouvaille avec une phrase courte."
    ],
    koVariant: "Cache le tresor en vue, avec un seul indice.",
    harderVariant: "Ajoute deux indices et une petite carte."
  },
  {
    id: "train-rouleaux",
    title: "Train des rouleaux",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["rouleaux papier toilette", "voitures"],
    skills: ["motricite", "imagination", "langage"],
    description: "Créer un train ou un tunnel avec des rouleaux.",
    steps: [
      "Aligne les rouleaux au sol.",
      "Fais passer une voiture dans le tunnel.",
      "Ajoute des gares imaginaires.",
      "L'enfant annonce les departs et arrivees."
    ],
    koVariant: "Un seul rouleau devient tunnel.",
    harderVariant: "Construis un circuit avec plusieurs tunnels et arrets."
  },
  {
    id: "pluie-dessins",
    title: "Pluie de dessins",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "rainy",
    messLevel: "low",
    materials: ["feuilles", "crayons"],
    skills: ["motricite", "emotions", "imagination"],
    description: "Dessiner la pluie, le soleil puis l'humeur du moment.",
    steps: [
      "Donne une feuille et quelques crayons.",
      "Propose de dessiner la meteo.",
      "Ajoute un visage content, calme ou fatigue.",
      "Nommez ensemble ce que le dessin raconte."
    ],
    koVariant: "Demande juste des traits de pluie et un soleil.",
    harderVariant: "Inventez une histoire courte a partir du dessin."
  },
  {
    id: "riz-qui-chuchote",
    title: "Riz qui chuchote",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["riz", "bols", "cuillere"],
    skills: ["motricite", "concentration", "autonomie"],
    description: "Ecouter et transvaser un petit fond de riz sec.",
    steps: [
      "Verse un petit fond de riz dans un bol.",
      "L'enfant remue doucement avec la cuillere.",
      "Ecoutez le bruit fort puis le bruit doux.",
      "Transvasez dans un deuxieme bol."
    ],
    koVariant: "Garde un seul bol et une petite quantite.",
    harderVariant: "Transvase sans faire tomber de grain."
  },
  {
    id: "livre-a-lenvers",
    title: "Livre a l'envers",
    ageMin: 1,
    ageMax: 6,
    duration: 5,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["livres"],
    skills: ["langage", "imagination", "emotions"],
    description: "Regarder un livre en inventant tout.",
    steps: [
      "Choisis un livre et ouvre une page au hasard.",
      "Demande ce que voit l'enfant.",
      "Invente une phrase tres courte.",
      "Tourne la page quand l'attention baisse."
    ],
    koVariant: "Laisse l'enfant pointer, tu nommes seulement les images.",
    harderVariant: "Demande un debut, un probleme et une fin."
  },
  {
    id: "carton-bateau",
    title: "Carton bateau",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["cartons", "doudous", "crayons"],
    skills: ["imagination", "motricite", "langage"],
    description: "Un carton devient bateau, bus ou fusee.",
    steps: [
      "Pose un carton ouvert au sol.",
      "L'enfant choisit le vehicule.",
      "Dessinez un volant ou des fenetres.",
      "Faites monter les doudous passagers."
    ],
    koVariant: "Le carton reste tel quel, l'enfant invente le trajet.",
    harderVariant: "Ajoute des tickets, une destination et un conducteur."
  },
  {
    id: "ombres-figurines",
    title: "Ombres de figurines",
    ageMin: 3,
    ageMax: 6,
    duration: 10,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["figurines", "feuilles", "crayons"],
    skills: ["concentration", "motricite", "imagination"],
    description: "Tracer le contour ou l'ombre des figurines.",
    steps: [
      "Pose une figurine sur une feuille.",
      "L'enfant trace autour avec un crayon.",
      "Retirez la figurine et regardez la forme.",
      "Ajoutez des yeux, roues ou details imaginaires."
    ],
    koVariant: "Trace un seul contour et laissez colorier.",
    harderVariant: "Fais deviner quelle figurine correspond a quel contour."
  },
  {
    id: "chaussette-marionnette",
    title: "Chaussette marionnette",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["chaussettes"],
    skills: ["langage", "emotions", "imagination"],
    description: "Une chaussette devient personnage express.",
    steps: [
      "Enfile une chaussette sur ta main.",
      "Donne-lui un nom tres simple.",
      "La marionnette pose une question a l'enfant.",
      "L'enfant repond ou prend la marionnette a son tour."
    ],
    koVariant: "La marionnette dit seulement bonjour et bonne nuit.",
    harderVariant: "Ajoute une emotion a jouer: timide, content, grognon."
  },
  {
    id: "course-cuilleres",
    title: "Course de cuilleres",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["cuillere", "bols"],
    skills: ["motricite", "concentration"],
    description: "Transporter des petits objets d'un bol a l'autre avec une cuillere.",
    steps: [
      "Place deux bols proches.",
      "Ajoute quelques petits objets legers.",
      "L'enfant les transporte avec une cuillere.",
      "Comptez les objets arrives."
    ],
    koVariant: "Utilise seulement un objet a deplacer.",
    harderVariant: "Eloigne les bols ou ajoute un obstacle."
  },
  {
    id: "garage-carton",
    title: "Garage en carton",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["cartons", "voitures"],
    skills: ["imagination", "motricite"],
    description: "Transformer un carton en mini garage.",
    steps: [
      "Pose un carton au sol.",
      "Dessine des places de parking.",
      "L'enfant gare les voitures.",
      "Inventez une panne ou une mission."
    ],
    koVariant: "Le carton devient juste une route.",
    harderVariant: "Ajoute des etages ou une station lavage."
  },
  {
    id: "danse-stop",
    title: "Danse stop",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "medium",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "concentration", "emotions"],
    description: "Danser puis s'immobiliser quand le parent dit stop.",
    steps: [
      "Lance une musique ou chante.",
      "Danse ensemble.",
      "Dis stop de temps en temps.",
      "Tout le monde se fige."
    ],
    koVariant: "Reste assis et donne les consignes.",
    harderVariant: "Ajoute des emotions a jouer."
  },
  {
    id: "train-chaises",
    title: "Train de chaises",
    ageMin: 2,
    ageMax: 5,
    duration: 15,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["chaises", "doudous"],
    skills: ["imagination", "langage"],
    description: "Les chaises deviennent un train imaginaire.",
    steps: [
      "Aligne quelques chaises.",
      "Choisissez une destination.",
      "Les doudous montent dans le train.",
      "Annoncez les arrets."
    ],
    koVariant: "Fais seulement un wagon.",
    harderVariant: "Ajoute des tickets et un controleur."
  },
  {
    id: "tri-cuillere-couleurs",
    title: "Tri de couleurs",
    ageMin: 1,
    ageMax: 4,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["bols", "cuillere"],
    skills: ["concentration", "autonomie"],
    description: "Trier des objets par couleur.",
    steps: [
      "Choisis quelques objets colores.",
      "Place un bol par couleur.",
      "L'enfant trie les objets.",
      "Nommez les couleurs ensemble."
    ],
    koVariant: "Utilise seulement deux couleurs.",
    harderVariant: "Ajoute une pince ou une cuillere."
  },
  {
    id: "route-scotch",
    title: "Route en scotch",
    ageMin: 2,
    ageMax: 6,
    duration: 20,
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["scotch", "voitures"],
    skills: ["motricite", "imagination"],
    description: "Creer une route au sol avec du scotch.",
    steps: [
      "Colle des bandes de scotch au sol.",
      "Dessine un trajet simple.",
      "Les voitures suivent la route.",
      "Ajoute un parking ou un tunnel."
    ],
    koVariant: "Fais une seule ligne droite.",
    harderVariant: "Ajoute croisements et regles."
  },
  {
    id: "animaux-cachettes",
    title: "Animaux cachettes",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["figurines"],
    skills: ["concentration", "langage"],
    description: "Chercher des animaux caches dans la piece.",
    steps: [
      "Cache quelques figurines.",
      "Donne un indice simple.",
      "L'enfant cherche.",
      "Change les cachettes."
    ],
    koVariant: "Cache une seule figurine.",
    harderVariant: "Ajoute des indices de couleur ou taille."
  },
  {
    id: "pile-livres",
    title: "Pile de livres",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["livres"],
    skills: ["motricite", "concentration"],
    description: "Empiler des livres doucement.",
    steps: [
      "Choisis quelques livres solides.",
      "Empilez-les ensemble.",
      "Comptez la hauteur.",
      "Faites tomber doucement."
    ],
    koVariant: "Empile seulement deux livres.",
    harderVariant: "Trie du plus petit au plus grand."
  },
  {
    id: "hop-coussins",
    title: "Sauts de coussins",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["coussins"],
    skills: ["motricite"],
    description: "Sauter de coussin en coussin sans toucher le sol.",
    steps: [
      "Pose des coussins espaces.",
      "Explique que le sol est de la lave.",
      "L'enfant saute.",
      "Change les distances."
    ],
    koVariant: "Deux coussins seulement.",
    harderVariant: "Ajoute un objet a transporter."
  },
  {
    id: "dessin-geant-carton",
    title: "Dessin geant carton",
    ageMin: 1,
    ageMax: 6,
    duration: 20,
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "medium",
    materials: ["cartons", "crayons"],
    skills: ["motricite", "imagination"],
    description: "Dessiner librement sur un grand carton.",
    steps: [
      "Pose un carton au sol.",
      "Donne quelques crayons.",
      "Dessinez ensemble.",
      "Nommez les formes."
    ],
    koVariant: "Laisse dessiner librement sans consigne.",
    harderVariant: "Dessine une ville ou une ferme."
  },
  {
    id: "mission-doudou-perdu",
    title: "Mission doudou perdu",
    thumbnail: "🧸",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise", "besoin-calme"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous"],
    skills: ["concentration", "langage", "imagination"],
    developmentGoals: ["observation", "memoire"],
    description: "Retrouver un doudou cache dans la maison.",
    steps: [
      "Cache un doudou dans une piece facile.",
      "Donne un indice simple.",
      "L'enfant cherche calmement.",
      "Le doudou remercie son sauveteur."
    ],
    koVariant: "Cache le doudou dans un endroit visible.",
    harderVariant: "Ajoute plusieurs indices ou plusieurs doudous."
  },
  {
    id: "autoroute-livres",
    title: "Autoroute de livres",
    thumbnail: "📚",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["livres", "voitures"],
    skills: ["motricite", "imagination"],
    developmentGoals: ["coordination"],
    description: "Construire une route avec des livres.",
    steps: [
      "Pose des livres ouverts ou fermes au sol.",
      "Cree un chemin pour les voitures.",
      "L'enfant suit la route doucement.",
      "Ajoute un tunnel ou un parking."
    ],
    koVariant: "Fais juste une ligne droite.",
    harderVariant: "Ajoute des ponts ou obstacles."
  },
  {
    id: "mission-couvertures",
    title: "Mission couvertures",
    thumbnail: "🛏️",
    ageMin: 1,
    ageMax: 4,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["coussins"],
    skills: ["motricite", "emotions"],
    developmentGoals: ["apaisement"],
    description: "Se cacher et ressortir sous une couverture.",
    steps: [
      "Pose une couverture ou des coussins.",
      "L'enfant se cache dessous.",
      "Fais coucou ou raconte une mini histoire.",
      "Inversez les roles."
    ],
    koVariant: "Reste allonge pendant le jeu.",
    harderVariant: "Ajoute une mission ou un objet cache."
  },
  {
    id: "tri-doudous",
    title: "Tri des doudous",
    thumbnail: "🧸",
    ageMin: 1,
    ageMax: 4,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous", "bols"],
    skills: ["concentration", "autonomie"],
    developmentGoals: ["tri", "observation"],
    description: "Classer les doudous selon leur taille ou couleur.",
    steps: [
      "Pose plusieurs doudous.",
      "Prepare deux zones ou bols.",
      "Trie ensemble les doudous.",
      "Comptez les groupes."
    ],
    koVariant: "Trie seulement grand et petit.",
    harderVariant: "Ajoute plusieurs categories."
  },
  {
    id: "musique-cuisine",
    title: "Musique de cuisine",
    thumbnail: "🥄",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 2,
    independenceLevel: "medium",
    noiseLevel: "high",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["bols", "cuillere"],
    skills: ["motricite", "imagination"],
    developmentGoals: ["rythme", "coordination"],
    description: "Faire un mini concert avec des objets de cuisine.",
    steps: [
      "Donne une cuillere et des bols.",
      "Tape doucement differents rythmes.",
      "L'enfant imite ou invente.",
      "Faites un mini concert."
    ],
    koVariant: "Limiter a un seul bol.",
    harderVariant: "Faire des rythmes a reproduire."
  },
  {
    id: "route-animaux",
    title: "Route des animaux",
    thumbnail: "🐘",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["figurines"],
    skills: ["motricite", "langage"],
    developmentGoals: ["imagination"],
    description: "Faire avancer des animaux avec des mouvements differents.",
    steps: [
      "Choisis quelques animaux.",
      "Imitez leur facon de marcher.",
      "Traversez la piece.",
      "Inventez une jungle ou une ferme."
    ],
    koVariant: "Faire seulement deux animaux.",
    harderVariant: "Ajoute une histoire complete."
  },
  {
    id: "livraison-secrete",
    title: "Livraison secrete",
    thumbnail: "📦",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["cartons", "doudous"],
    skills: ["motricite", "autonomie"],
    developmentGoals: ["coordination"],
    description: "Transporter des objets d'un point a un autre.",
    steps: [
      "Prepare un carton ou panier.",
      "Ajoute quelques objets legers.",
      "L'enfant livre les objets.",
      "Change les destinations."
    ],
    koVariant: "Une seule livraison.",
    harderVariant: "Ajoute des obstacles."
  },
  {
    id: "village-figurines",
    title: "Village de figurines",
    thumbnail: "🏠",
    ageMin: 3,
    ageMax: 6,
    duration: 20,
    setupTime: 3,
    cleanupTime: 2,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["figurines", "cartons"],
    skills: ["imagination", "langage"],
    developmentGoals: ["narration"],
    description: "Construire un petit village imaginaire.",
    steps: [
      "Dispose des cartons comme maisons.",
      "Ajoute les figurines.",
      "Inventez qui habite ou travaille ici.",
      "Creez une mini aventure."
    ],
    koVariant: "Construire une seule maison.",
    harderVariant: "Ajoute routes et missions."
  },
  {
    id: "defi-silence",
    title: "Defi silence",
    thumbnail: "🤫",
    ageMin: 3,
    ageMax: 6,
    duration: 5,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["concentration", "emotions"],
    developmentGoals: ["self-control"],
    description: "Ecouter les sons autour de soi en silence.",
    steps: [
      "Asseyez-vous confortablement.",
      "Ecoutez les sons pendant quelques secondes.",
      "Nommez ce que vous entendez.",
      "Essayez encore."
    ],
    koVariant: "Faire seulement 10 secondes.",
    harderVariant: "Fermer les yeux."
  },
  {
    id: "mission-rouleaux",
    title: "Mission rouleaux",
    thumbnail: "🧻",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["rouleaux papier toilette"],
    skills: ["motricite"],
    developmentGoals: ["coordination"],
    description: "Empiler ou faire rouler des rouleaux.",
    steps: [
      "Pose quelques rouleaux.",
      "Construisez une tour.",
      "Faites rouler ou tomber doucement.",
      "Recommencez differemment."
    ],
    koVariant: "Utilise seulement trois rouleaux.",
    harderVariant: "Ajoute une cible."
  },
  {
    id: "parade-doudous",
    title: "Parade des doudous",
    thumbnail: "🎉",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous"],
    skills: ["langage", "imagination"],
    developmentGoals: ["socialisation"],
    description: "Faire defiler les doudous dans une parade.",
    steps: [
      "Choisissez plusieurs doudous.",
      "Faites-les marcher ensemble.",
      "Annoncez leur nom ou talent.",
      "Terminez par une danse."
    ],
    koVariant: "Faire marcher un seul doudou.",
    harderVariant: "Ajoute une musique ou un public."
  },
  {
    id: "pont-coussins",
    title: "Pont de coussins",
    thumbnail: "🌉",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["coussins"],
    skills: ["motricite", "concentration"],
    developmentGoals: ["equilibre"],
    description: "Traverser un pont de coussins sans tomber.",
    steps: [
      "Aligne les coussins.",
      "Explique la mission.",
      "Traverse sans toucher le sol.",
      "Change la difficulte."
    ],
    koVariant: "Pont tres court.",
    harderVariant: "Transporter un objet."
  },
  {
    id: "photo-imaginaire",
    title: "Photo imaginaire",
    thumbnail: "📸",
    ageMin: 2,
    ageMax: 6,
    duration: 5,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["imagination", "langage"],
    developmentGoals: ["expression"],
    description: "Faire semblant de prendre des photos imaginaires.",
    steps: [
      "Fais un cadre avec tes mains.",
      "Cherche quelque chose a photographier.",
      "Explique ce que tu vois.",
      "Change de sujet."
    ],
    koVariant: "Photographier seulement des objets rouges.",
    harderVariant: "Inventer une exposition photo."
  },
  {
    id: "animaux-endormis",
    title: "Animaux endormis",
    thumbnail: "😴",
    ageMin: 1,
    ageMax: 4,
    duration: 10,
    setupTime: 1,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["figurines", "doudous"],
    skills: ["emotions", "langage"],
    developmentGoals: ["apaisement"],
    description: "Faire dormir les animaux ou doudous.",
    steps: [
      "Installe un coin calme.",
      "Couche les animaux.",
      "Chante doucement ou raconte une mini histoire.",
      "Souhaite bonne nuit."
    ],
    koVariant: "Faire dormir un seul doudou.",
    harderVariant: "Inventer un reve pour chaque animal."
  },
  {
    id: "mission-formes",
    title: "Mission formes",
    thumbnail: "🔺",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["feuilles", "crayons"],
    skills: ["concentration", "motricite"],
    developmentGoals: ["formes", "observation"],
    description: "Dessiner et reconnaitre des formes simples.",
    steps: [
      "Dessine un cercle ou carre.",
      "L'enfant retrouve des formes similaires autour de lui.",
      "Ajoutez d'autres formes.",
      "Inventez un personnage avec elles."
    ],
    koVariant: "Faire seulement des cercles.",
    harderVariant: "Combiner plusieurs formes."
  },
  {
    id: "mission-escargot",
    title: "Mission escargot",
    thumbnail: "🐌",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "concentration"],
    developmentGoals: ["controle-mouvement"],
    description: "Bouger le plus lentement possible comme un escargot.",
    steps: [
      "Choisissez un point de depart.",
      "Avancez tres lentement.",
      "Essayez de ne pas accelerer.",
      "Ajoutez des mouvements rigolos."
    ],
    koVariant: "Faire seulement quelques pas.",
    harderVariant: "Transporter un objet sans le faire tomber."
  },
  {
    id: "cuisine-doudous",
    title: "Cuisine des doudous",
    thumbnail: "🍲",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 2,
    independenceLevel: "high",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "medium",
    materials: ["doudous", "bols", "cuillere"],
    skills: ["imagination", "langage"],
    developmentGoals: ["jeu-symbolique"],
    description: "Preparer des repas imaginaires pour les doudous.",
    steps: [
      "Installe les bols devant les doudous.",
      "L'enfant prepare un repas imaginaire.",
      "Chaque doudou donne son avis.",
      "Ajoutez un dessert rigolo."
    ],
    koVariant: "Servir un seul doudou.",
    harderVariant: "Faire un vrai menu complet."
  },
  {
    id: "ligne-magique",
    title: "Ligne magique",
    thumbnail: "〰️",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["scotch"],
    skills: ["motricite", "equilibre"],
    developmentGoals: ["coordination"],
    description: "Suivre une ligne au sol sans sortir du chemin.",
    steps: [
      "Colle une ligne de scotch au sol.",
      "Marchez dessus doucement.",
      "Essayez differents styles de marche.",
      "Ajoutez des virages."
    ],
    koVariant: "Faire une ligne droite.",
    harderVariant: "Marcher a reculons."
  },
  {
    id: "safari-salon",
    title: "Safari du salon",
    thumbnail: "🦁",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["figurines"],
    skills: ["imagination", "langage"],
    developmentGoals: ["observation"],
    description: "Explorer un safari imaginaire dans la maison.",
    steps: [
      "Cache quelques animaux.",
      "Partez en expedition.",
      "Imitez les cris ou mouvements.",
      "Racontez ce que vous voyez."
    ],
    koVariant: "Chercher seulement un animal.",
    harderVariant: "Ajouter une mission photo imaginaire."
  },
  {
    id: "construction-bols",
    title: "Construction de bols",
    thumbnail: "🥣",
    ageMin: 1,
    ageMax: 4,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["bols"],
    skills: ["motricite", "concentration"],
    developmentGoals: ["coordination"],
    description: "Empiler et renverser des bols.",
    steps: [
      "Empile les bols doucement.",
      "Observe la hauteur.",
      "Fais tomber doucement.",
      "Recommence autrement."
    ],
    koVariant: "Utiliser deux bols seulement.",
    harderVariant: "Faire une pyramide."
  },
  {
    id: "voitures-garage",
    title: "Voitures au garage",
    thumbnail: "🚗",
    ageMin: 2,
    ageMax: 5,
    duration: 15,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["voitures", "cartons"],
    skills: ["imagination", "autonomie"],
    developmentGoals: ["jeu-symbolique"],
    description: "Faire rentrer les voitures dans un garage imaginaire.",
    steps: [
      "Prepare un carton comme garage.",
      "Les voitures rentrent une par une.",
      "Ajoute une station lavage ou essence.",
      "Invente des petites pannes."
    ],
    koVariant: "Faire seulement un parking.",
    harderVariant: "Ajouter plusieurs etages."
  },
  {
    id: "parcours-animaux",
    title: "Parcours animaux",
    thumbnail: "🐒",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "motivated",
    weather: "indoor",
    messLevel: "medium",
    materials: ["coussins"],
    skills: ["motricite"],
    developmentGoals: ["coordination", "equilibre"],
    description: "Faire un parcours avec des mouvements d'animaux.",
    steps: [
      "Prepare quelques obstacles.",
      "Saute comme une grenouille.",
      "Rampe comme un serpent.",
      "Marche comme un elephant."
    ],
    koVariant: "Faire deux animaux seulement.",
    harderVariant: "Ajouter des missions chronometrees."
  },
  {
    id: "dessin-ombres",
    title: "Dessin d'ombres",
    thumbnail: "✏️",
    ageMin: 3,
    ageMax: 6,
    duration: 15,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "sunny",
    messLevel: "low",
    materials: ["feuilles", "crayons", "figurines"],
    skills: ["motricite", "concentration"],
    developmentGoals: ["precision"],
    description: "Tracer les ombres des objets ou figurines.",
    steps: [
      "Place une figurine pres de la lumiere.",
      "Observe son ombre.",
      "Trace doucement autour.",
      "Ajoute des details rigolos."
    ],
    koVariant: "Tracer une seule ombre.",
    harderVariant: "Faire deviner les objets traces."
  },
  {
    id: "mission-panier",
    title: "Mission panier",
    thumbnail: "🧺",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["chaussettes"],
    skills: ["motricite"],
    developmentGoals: ["adresse"],
    description: "Lancer des chaussettes dans un panier.",
    steps: [
      "Fais des boules avec des chaussettes.",
      "Place un panier ou une boite.",
      "Lance les chaussettes.",
      "Compte les reussites."
    ],
    koVariant: "Panier tres proche.",
    harderVariant: "Reculer ou viser plusieurs paniers."
  },
  {
    id: "histoire-image",
    title: "Histoire d'image",
    thumbnail: "📖",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: ["livres"],
    skills: ["langage", "imagination"],
    developmentGoals: ["narration"],
    description: "Inventer une histoire a partir d'une image.",
    steps: [
      "Ouvre un livre au hasard.",
      "Choisis une image.",
      "Imagine ce qu'il se passe.",
      "Ajoute une fin rigolote."
    ],
    koVariant: "Faire une phrase courte.",
    harderVariant: "Inventer debut, milieu et fin."
  },
  {
    id: "course-doudous",
    title: "Course des doudous",
    thumbnail: "🏁",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "indoor",
    messLevel: "low",
    materials: ["doudous"],
    skills: ["motricite", "imagination"],
    developmentGoals: ["coordination"],
    description: "Faire courir les doudous dans une mini course.",
    steps: [
      "Choisissez plusieurs doudous.",
      "Preparez une ligne de depart.",
      "Lancez la course.",
      "Annoncez le gagnant."
    ],
    koVariant: "Faire une course tres courte.",
    harderVariant: "Ajouter obstacles ou relais."
  },
  {
    id: "tour-chaussettes",
    title: "Tour de chaussettes",
    thumbnail: "🧦",
    ageMin: 1,
    ageMax: 4,
    duration: 5,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["chaussettes"],
    skills: ["motricite", "concentration"],
    developmentGoals: ["precision"],
    description: "Empiler des boules de chaussettes.",
    steps: [
      "Fais plusieurs boules de chaussettes.",
      "Empile-les doucement.",
      "Observe si la tour tient.",
      "Fais tomber doucement."
    ],
    koVariant: "Faire une mini tour.",
    harderVariant: "Empiler le plus haut possible."
  },
  {
    id: "balade-imaginaire",
    title: "Balade imaginaire",
    thumbnail: "🌈",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["imagination", "langage"],
    developmentGoals: ["expression"],
    description: "Imaginer une promenade dans un monde fantastique.",
    steps: [
      "Choisissez un endroit imaginaire.",
      "Decris ce que vous voyez.",
      "Ajoute un animal ou personnage.",
      "Continue ensemble."
    ],
    koVariant: "Faire une seule scene.",
    harderVariant: "Inventer une aventure complete."
  },
  {
    id: "mission-rangement",
    title: "Mission rangement",
    thumbnail: "🧹",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "indoor",
    messLevel: "low",
    materials: ["jouets"],
    skills: ["autonomie"],
    developmentGoals: ["organisation"],
    description: "Transformer le rangement en mission.",
    steps: [
      "Choisis une mission simple.",
      "Range les jouets par famille.",
      "Compte les objets ranges.",
      "Celebre la mission terminee."
    ],
    koVariant: "Ranger seulement cinq objets.",
    harderVariant: "Ajouter un chrono doux."
  },
  {
    id: "mini-yoga-animaux",
    title: "Mini yoga animaux",
    thumbnail: "🧘",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "medium",
    weather: "any",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "emotions"],
    developmentGoals: ["equilibre", "respiration"],
    description: "Faire des poses simples inspirees des animaux.",
    steps: [
      "Choisissez un animal.",
      "Imitez sa posture.",
      "Respirez doucement.",
      "Passez a un autre animal."
    ],
    koVariant: "Faire deux poses seulement.",
    harderVariant: "Faire un mini enchainement."
  },
  {
    id: "chasse-feuilles",
    title: "Chasse aux feuilles",
    thumbnail: "🍂",
    ageMin: 2,
    ageMax: 6,
    duration: 20,
    setupTime: 1,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "medium",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme", "patient"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["observation", "motricite"],
    developmentGoals: ["nature", "tri"],
    description: "Ramasser des feuilles differentes pendant une balade.",
    steps: [
      "Choisissez une zone exterieure calme.",
      "Cherchez des feuilles de tailles ou couleurs differentes.",
      "Comparez-les ensemble.",
      "Faites une mini collection."
    ],
    koVariant: "Trouver seulement trois feuilles.",
    harderVariant: "Classer par forme ou couleur."
  },
  {
    id: "course-cailloux",
    title: "Course de cailloux",
    thumbnail: "🪨",
    ageMin: 2,
    ageMax: 5,
    duration: 15,
    setupTime: 1,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "concentration"],
    developmentGoals: ["coordination"],
    description: "Transporter des petits cailloux d'un point a un autre.",
    steps: [
      "Dessine deux zones au sol.",
      "Ramasse quelques petits cailloux.",
      "L'enfant les transporte un par un.",
      "Comptez les allers-retours."
    ],
    koVariant: "Transporter seulement trois cailloux.",
    harderVariant: "Ajouter une cuillere pour transporter."
  },
  {
    id: "mission-flaques",
    title: "Mission flaques",
    thumbnail: "💦",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 0,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "high",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "rainy",
    messLevel: "high",
    materials: [],
    skills: ["motricite"],
    developmentGoals: ["equilibre"],
    description: "Sauter dans les flaques et observer les eclaboussures.",
    steps: [
      "Trouvez une petite flaque securisee.",
      "Sautez dedans ensemble.",
      "Comparez les tailles d'eclaboussures.",
      "Cherchez la plus grande flaque."
    ],
    koVariant: "Marcher seulement autour des flaques.",
    harderVariant: "Faire un parcours de flaques."
  },
  {
    id: "mission-baton",
    title: "Mission baton magique",
    thumbnail: "🪵",
    ageMin: 2,
    ageMax: 6,
    duration: 20,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["imagination", "motricite"],
    developmentGoals: ["creativite"],
    description: "Trouver un baton et imaginer ses pouvoirs.",
    steps: [
      "Cherchez un baton au sol.",
      "Imaginez ce qu'il peut faire.",
      "Transformez-le en baguette ou outil magique.",
      "Inventez une mission."
    ],
    koVariant: "Trouver un seul baton.",
    harderVariant: "Creer une histoire complete."
  },
  {
    id: "parcours-bancs",
    title: "Parcours de bancs",
    thumbnail: "🛝",
    ageMin: 3,
    ageMax: 6,
    duration: 15,
    setupTime: 1,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "motivated",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "equilibre"],
    developmentGoals: ["coordination"],
    description: "Transformer les bancs et bordures en parcours moteur.",
    steps: [
      "Choisissez une zone securisee.",
      "Marchez sur les bordures.",
      "Sautez de repere en repere.",
      "Ajoutez des defis simples."
    ],
    koVariant: "Faire seulement une ligne droite.",
    harderVariant: "Ajouter des mouvements d'animaux."
  },
  {
    id: "restaurant-herbe",
    title: "Restaurant dans l'herbe",
    thumbnail: "🌼",
    ageMin: 2,
    ageMax: 5,
    duration: 20,
    setupTime: 2,
    cleanupTime: 1,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "medium",
    materials: ["bols", "cuillere"],
    skills: ["imagination", "langage"],
    developmentGoals: ["jeu-symbolique"],
    description: "Faire semblant de cuisiner avec des elements naturels.",
    steps: [
      "Ramasse quelques feuilles ou fleurs tombees.",
      "Prepare une soupe imaginaire.",
      "Servez les doudous ou le parent.",
      "Inventez les saveurs."
    ],
    koVariant: "Faire une seule recette.",
    harderVariant: "Ajouter un menu complet."
  },
  {
    id: "cherche-couleurs-dehors",
    title: "Cherche couleurs dehors",
    thumbnail: "🌈",
    ageMin: 1,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["epuise"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["observation", "langage"],
    developmentGoals: ["vocabulaire"],
    description: "Trouver des couleurs dans la nature ou la rue.",
    steps: [
      "Choisissez une couleur.",
      "Cherchez des objets ou plantes de cette couleur.",
      "Nommez-les ensemble.",
      "Changez de couleur."
    ],
    koVariant: "Faire deux couleurs seulement.",
    harderVariant: "Chercher des nuances."
  },
  {
    id: "livraison-feuilles",
    title: "Livraison de feuilles",
    thumbnail: "🍃",
    ageMin: 2,
    ageMax: 5,
    duration: 15,
    setupTime: 1,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["motricite"],
    developmentGoals: ["coordination"],
    description: "Transporter des feuilles d'un endroit a un autre.",
    steps: [
      "Fais deux zones au sol.",
      "Ramasse des feuilles.",
      "Transporte-les rapidement.",
      "Compte les livraisons."
    ],
    koVariant: "Transporter seulement quelques feuilles.",
    harderVariant: "Ajouter un parcours."
  },
  {
    id: "ombres-dehors",
    title: "Course aux ombres",
    thumbnail: "☀️",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "sunny",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "observation"],
    developmentGoals: ["coordination"],
    description: "Courir et sauter sur les ombres.",
    steps: [
      "Observez les ombres au sol.",
      "Essayez de marcher dessus.",
      "Sautez d'une ombre a l'autre.",
      "Inventez des regles rigolotes."
    ],
    koVariant: "Marcher doucement seulement.",
    harderVariant: "Eviter certaines ombres."
  },
  {
    id: "cabane-nature",
    title: "Cabane nature",
    thumbnail: "🌿",
    ageMin: 3,
    ageMax: 6,
    duration: 30,
    setupTime: 3,
    cleanupTime: 2,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "motivated",
    weather: "outdoor",
    messLevel: "medium",
    materials: [],
    skills: ["imagination", "motricite"],
    developmentGoals: ["cooperation"],
    description: "Construire une mini cabane avec des elements naturels.",
    steps: [
      "Ramassez quelques branches tombees.",
      "Choisissez un coin calme.",
      "Assemblez une mini cabane.",
      "Installez un doudou dedans."
    ],
    koVariant: "Faire juste un mini abri.",
    harderVariant: "Ajouter une entree et un decor."
  },
  {
    id: "mission-escaliers",
    title: "Mission escaliers",
    thumbnail: "🪜",
    ageMin: 2,
    ageMax: 5,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "medium",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-defoulement"],
    parentEnergy: "medium",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["motricite"],
    developmentGoals: ["equilibre"],
    description: "Monter et descendre quelques marches doucement.",
    steps: [
      "Choisissez un petit escalier securise.",
      "Montez doucement.",
      "Descendez en comptant.",
      "Essayez differents rythmes."
    ],
    koVariant: "Faire seulement quelques marches.",
    harderVariant: "Monter comme un animal."
  },
  {
    id: "cherche-insectes",
    title: "Cherche insectes",
    thumbnail: "🐞",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["observation", "langage"],
    developmentGoals: ["nature"],
    description: "Observer les petits insectes dehors.",
    steps: [
      "Cherchez dans l'herbe ou pres des fleurs.",
      "Observez doucement.",
      "Nommez les couleurs ou formes.",
      "Laissez les insectes tranquilles."
    ],
    koVariant: "Observer un seul insecte.",
    harderVariant: "Comparer plusieurs insectes."
  },
  {
    id: "danse-vent",
    title: "Danse du vent",
    thumbnail: "🌬️",
    ageMin: 2,
    ageMax: 6,
    duration: 10,
    setupTime: 0,
    cleanupTime: 0,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: false,
    screenFree: true,
    parentMood: ["besoin-calme"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "low",
    materials: [],
    skills: ["motricite", "emotions"],
    developmentGoals: ["expression-corporelle"],
    description: "Bouger comme le vent dans un espace exterieur.",
    steps: [
      "Levez les bras doucement.",
      "Bougez lentement comme le vent.",
      "Accelerez ou ralentissez.",
      "Inventez une tempete ou une brise."
    ],
    koVariant: "Faire seulement des mouvements de bras.",
    harderVariant: "Ajouter musique ou foulards."
  },
  {
    id: "mini-picnic",
    title: "Mini picnic",
    thumbnail: "🧺",
    ageMin: 2,
    ageMax: 6,
    duration: 20,
    setupTime: 3,
    cleanupTime: 3,
    independenceLevel: "high",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "medium",
    weather: "outdoor",
    messLevel: "medium",
    materials: ["doudous", "bols"],
    skills: ["autonomie", "imagination"],
    developmentGoals: ["socialisation"],
    description: "Organiser un mini picnic avec les doudous.",
    steps: [
      "Installez une couverture.",
      "Invitez les doudous.",
      "Servez un gouter ou repas imaginaire.",
      "Profitez du moment dehors."
    ],
    koVariant: "Faire un picnic tres court.",
    harderVariant: "Ajouter jeux ou chansons."
  },
  {
    id: "mission-traces",
    title: "Mission traces",
    thumbnail: "👣",
    ageMin: 2,
    ageMax: 6,
    duration: 15,
    setupTime: 0,
    cleanupTime: 1,
    independenceLevel: "medium",
    noiseLevel: "low",
    requiresSupervision: true,
    screenFree: true,
    parentMood: ["patient"],
    parentEnergy: "ko",
    weather: "outdoor",
    messLevel: "medium",
    materials: [],
    skills: ["observation", "motricite"],
    developmentGoals: ["nature", "curiosite"],
    description: "Chercher et suivre des traces ou marques au sol.",
    steps: [
      "Observez le sol ensemble.",
      "Cherchez des traces interessantes.",
      "Suivez-les quelques metres.",
      "Imaginez qui est passe ici."
    ],
    koVariant: "Observer seulement quelques traces.",
    harderVariant: "Inventer une histoire detective."
  }
];

const metadataOverrides: Record<string, Partial<ActivityMetadata>> = {
  "mission-chaussettes": { thumbnail: "🧦", independenceLevel: "high", parentMood: ["epuise", "besoin-calme"] },
  "restaurant-doudous": { thumbnail: "🧸", independenceLevel: "medium" },
  "parcours-ninja-salon": { thumbnail: "🥷", noiseLevel: "high", parentMood: ["besoin-defoulement"] },
  "chasse-couleurs": { thumbnail: "🌈", setupTime: 0, cleanupTime: 0, independenceLevel: "high" },
  "bain-animaux": { thumbnail: "🛁", requiresSupervision: true, season: ["summer", "winter"] },
  "boite-mystere": { thumbnail: "📦" },
  "parking-geant": { thumbnail: "🚗" },
  "yoga-rigolo": { thumbnail: "🧘", setupTime: 0, cleanupTime: 0, noiseLevel: "low" },
  "courrier-secret": { thumbnail: "✉️" },
  "transvasement-baignoire": { thumbnail: "💧", requiresSupervision: true, season: ["summer", "winter"] },
  "cuisine-imaginaire": { thumbnail: "🥣" },
  "theatre-emotions": { thumbnail: "🎭" },
  "course-glacons": { thumbnail: "🧊", requiresSupervision: true, season: ["summer"] },
  "sauvetage-jouets": { thumbnail: "🚑" },
  "tri-pinces-linge": { thumbnail: "🧺", independenceLevel: "high" },
  "cabane-express": { thumbnail: "⛺" },
  "cherche-trouve-maison": { thumbnail: "🔎", setupTime: 0, cleanupTime: 0, independenceLevel: "high" },
  "peche-bouchons": { thumbnail: "🎣", requiresSupervision: true, season: ["summer", "winter"] },
  "tour-coussins": { thumbnail: "🛋️" },
  "mini-chasse-tresor": { thumbnail: "🗺️" },
  "train-rouleaux": { thumbnail: "🚂" },
  "pluie-dessins": { thumbnail: "🌧️", season: ["autumn", "winter", "spring"] },
  "riz-qui-chuchote": { thumbnail: "🌾", cleanupTime: 5 },
  "livre-a-lenvers": { thumbnail: "📚", setupTime: 0, cleanupTime: 0, independenceLevel: "medium" },
  "carton-bateau": { thumbnail: "⛵" },
  "ombres-figurines": { thumbnail: "🦖" },
  "chaussette-marionnette": { thumbnail: "🧦" },
  "course-cuilleres": { thumbnail: "🥄", independenceLevel: "medium" },
  "garage-carton": { thumbnail: "🏠" },
  "danse-stop": { thumbnail: "🕺", noiseLevel: "high", parentMood: ["besoin-defoulement", "patient"] },
  "train-chaises": { thumbnail: "🚆", noiseLevel: "medium" },
  "tri-cuillere-couleurs": { thumbnail: "🔴", independenceLevel: "high" },
  "route-scotch": { thumbnail: "🛣️", cleanupTime: 2 },
  "animaux-cachettes": { thumbnail: "🐾", independenceLevel: "medium" },
  "pile-livres": { thumbnail: "📚", independenceLevel: "medium" },
  "hop-coussins": { thumbnail: "🔥", noiseLevel: "high", parentMood: ["besoin-defoulement"] },
  "dessin-geant-carton": { thumbnail: "🖍️", cleanupTime: 4 }
};

const materialThumbnails: Array<[string, string]> = [
  ["chaussettes", "🧦"],
  ["doudous", "🧸"],
  ["eau", "💧"],
  ["figurines", "🐾"],
  ["voitures", "🚗"],
  ["livres", "📚"],
  ["cartons", "📦"],
  ["coussins", "🛋️"],
  ["crayons", "🖍️"],
  ["bols", "🥣"],
  ["cuillere", "🥄"],
  ["scotch", "🧷"]
];

const skillGoalMap: Record<string, DevelopmentGoal[]> = {
  motricite: ["motricite-globale", "coordination"],
  concentration: ["attention"],
  autonomie: ["autonomie"],
  langage: ["langage"],
  emotions: ["gestion-emotions"],
  imagination: ["imagination"],
  social: ["cooperation", "socialisation"],
  logique: ["resolution-problemes", "attention"],
  construction: ["creativite", "projection"]
};

const unique = <T,>(values: T[]) => [...new Set(values)];

const inferThumbnail = (activity: BaseActivity) => {
  const title = activity.title.toLocaleLowerCase("fr-FR");
  if (title.includes("yoga")) return "🧘";
  if (title.includes("couleur")) return "🌈";
  if (title.includes("train")) return "🚂";
  if (title.includes("danse")) return "🕺";

  const matchedMaterial = materialThumbnails.find(([material]) => activity.materials.includes(material));
  return matchedMaterial?.[1] ?? "✨";
};

const inferSetupTime = (activity: BaseActivity) => {
  if (activity.materials.length === 0) return 0;
  const base = activity.materials.length <= 1 ? 1 : 2;
  return activity.messLevel === "medium" ? base + 1 : base;
};

const inferCleanupTime = (activity: BaseActivity) => {
  const messCleanup = activity.messLevel === "low" ? 1 : activity.messLevel === "medium" ? 4 : 8;
  const waterBonus = activity.materials.includes("eau") || activity.materials.includes("riz") ? 2 : 0;
  return messCleanup + waterBonus;
};

const inferIndependenceLevel = (activity: BaseActivity): IndependenceLevel => {
  if (activity.ageMin <= 1 || activity.materials.includes("eau") || activity.parentEnergy === "motivated") return "low";
  if (activity.skills.includes("autonomie") && activity.messLevel === "low") return "high";
  return "medium";
};

const inferNoiseLevel = (activity: BaseActivity): NoiseLevel => {
  const title = activity.title.toLocaleLowerCase("fr-FR");
  if (activity.parentEnergy === "motivated" || title.includes("danse") || title.includes("sauts")) return "high";
  if (activity.skills.includes("motricite") || activity.messLevel === "medium") return "medium";
  return "low";
};

const inferRequiresSupervision = (activity: BaseActivity) => {
  return activity.ageMin <= 2 || activity.materials.includes("eau") || activity.materials.includes("scotch") || activity.parentEnergy === "motivated";
};

const inferDevelopmentGoals = (activity: BaseActivity): DevelopmentGoal[] => {
  const goals = activity.skills.flatMap((skill) => skillGoalMap[skill] ?? []);
  if (activity.materials.some((material) => ["cuillere", "pinces a linge", "crayons"].includes(material))) {
    goals.push("motricite-fine");
  }
  return unique(goals);
};

const inferSeason = (activity: BaseActivity): Season[] => {
  if (activity.weather === "rainy") return ["autumn", "winter", "spring"];
  if (activity.weather === "sunny") return ["spring", "summer"];
  if (activity.materials.includes("eau")) return ["summer"];
  return ["all-season"];
};

const inferParentMood = (activity: BaseActivity, noiseLevel: NoiseLevel): ParentMood[] => {
  const moods: ParentMood[] = [];
  if (activity.parentEnergy === "ko") moods.push("epuise");
  if (activity.parentEnergy === "medium") moods.push("patient");
  if (noiseLevel === "low") moods.push("besoin-calme");
  if (noiseLevel === "high") moods.push("besoin-defoulement");
  return unique(moods.length > 0 ? moods : ["patient"]);
};

const inferGroupActivity = (activity: BaseActivity) => {
  return activity.skills.includes("social") || activity.developmentGoals?.includes("cooperation") || activity.ageMax >= 8;
};

const inferPlayerCountMin = (activity: BaseActivity, groupActivity: boolean) => {
  return groupActivity ? 1 : 1;
};

const inferPlayerCountMax = (activity: BaseActivity, groupActivity: boolean) => {
  if (activity.playerCountMax) return activity.playerCountMax;
  if (!groupActivity) return 2;
  if (activity.ageMax >= 8) return 6;
  return 4;
};

const inferActivityType = (activity: BaseActivity, noiseLevel: NoiseLevel): ActivityType => {
  const title = activity.title.toLocaleLowerCase("fr-FR");
  if (activity.weather === "outdoor" || activity.weather === "sunny") return "outdoor";
  if (activity.skills.includes("social")) return "social";
  if (activity.skills.includes("construction") || activity.materials.some((material) => ["cartons", "scotch", "rouleaux papier toilette"].includes(material))) return "construction";
  if (activity.skills.includes("logique") || title.includes("mystere") || title.includes("secret")) return "investigation";
  if (activity.parentMood?.includes("besoin-defoulement") || noiseLevel === "high") return "challenge";
  if (activity.skills.includes("motricite")) return "motor";
  if (activity.skills.includes("imagination") || activity.materials.some((material) => ["feuilles", "crayons"].includes(material))) return "creative";
  if (activity.materials.includes("eau") || activity.materials.includes("riz")) return "sensory";
  if (noiseLevel === "low") return "calm";
  return "story";
};

const enrichActivity = (activity: BaseActivity): Activity => {
  const override = metadataOverrides[activity.id] ?? {};
  const noiseLevel = override.noiseLevel ?? activity.noiseLevel ?? inferNoiseLevel(activity);
  const groupActivity = override.groupActivity ?? activity.groupActivity ?? inferGroupActivity(activity);

  return {
    ...activity,
    thumbnail: override.thumbnail ?? activity.thumbnail ?? inferThumbnail(activity),
    image: override.image ?? activity.image,
    setupTime: override.setupTime ?? activity.setupTime ?? inferSetupTime(activity),
    cleanupTime: override.cleanupTime ?? activity.cleanupTime ?? inferCleanupTime(activity),
    independenceLevel: override.independenceLevel ?? activity.independenceLevel ?? inferIndependenceLevel(activity),
    noiseLevel,
    requiresSupervision: override.requiresSupervision ?? activity.requiresSupervision ?? inferRequiresSupervision(activity),
    screenFree: override.screenFree ?? activity.screenFree ?? true,
    groupActivity,
    playerCountMin: override.playerCountMin ?? activity.playerCountMin ?? inferPlayerCountMin(activity, groupActivity),
    playerCountMax: override.playerCountMax ?? activity.playerCountMax ?? inferPlayerCountMax(activity, groupActivity),
    activityType: override.activityType ?? activity.activityType ?? inferActivityType(activity, noiseLevel),
    developmentGoals: override.developmentGoals ?? activity.developmentGoals ?? inferDevelopmentGoals(activity),
    season: override.season ?? activity.season ?? inferSeason(activity),
    parentMood: override.parentMood ?? activity.parentMood ?? inferParentMood(activity, noiseLevel),
    source: override.source ?? activity.source ?? "proposed"
  };
};

export const activities: Activity[] = baseActivities.map(enrichActivity);
