const REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bCreer\b/g, 'Créer'],
  [/\bcreer\b/g, 'créer'],
  [/\bemission\b/g, 'émission'],
  [/\benergie\b/g, 'énergie'],
  [/\bpreparation\b/g, 'préparation'],
  [/\bregles\b/g, 'règles'],
  [/\btres\b/g, 'très'],
  [/\betre\b/g, 'être'],
  [/\bchronometre\b/g, 'chronomètre'],
  [/\bchronometrees\b/g, 'chronométrées'],
  [/\bResoudre\b/g, 'Résoudre'],
  [/\bresoudre\b/g, 'résoudre'],
  [/\benigmes\b/g, 'énigmes'],
  [/\btresor\b/g, 'trésor'],
  [/\bproces\b/g, 'procès'],
  [/\bdefi\b/g, 'défi'],
  [/\bdefis\b/g, 'défis'],
  [/\bbatiments\b/g, 'bâtiments'],
  [/\bverifie\b/g, 'vérifie'],
  [/\bdifferents\b/g, 'différents'],
  [/\bsecurite\b/g, 'sécurité'],
  [/\bpates\b/g, 'pâtes'],
  [/\bTheatre\b/g, 'Théâtre'],
  [/\btheatre\b/g, 'théâtre'],
  [/\bemotions\b/g, 'émotions'],
  [/\bpiece\b/g, 'pièce'],
  [/\bEcoutez\b/g, 'Écoutez'],
  [/\becoutez\b/g, 'écoutez'],
  [/\bfenetres\b/g, 'fenêtres'],
  [/\bequilibre\b/g, 'équilibre'],
  [/\bmemoire\b/g, 'mémoire'],
  [/\bmotricite\b/g, 'motricité'],
  [/\bexterieure\b/g, 'extérieure'],
  [/\bexterieur\b/g, 'extérieur'],
  [/\binspirees\b/g, 'inspirées'],
  [/\bmetres\b/g, 'mètres'],
  [/\bidee\b/g, 'idée'],
  [/\bIdee\b/g, 'Idée'],
  [/\bcomplete\b/g, 'complète'],
  [/\ba partir\b/g, 'à partir'],
  [/\ba jouer\b/g, 'à jouer'],
];

export function formatActivityText(value: string) {
  return REPLACEMENTS.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}
